/* AboutDialog.c generated by valac 0.34.7, the Vala compiler
 * generated from AboutDialog.vala, do not modify */

/* Copyright 2014-2017 Go For It! developers
*
* This file is part of Go For It!.
*
* Go For It! is free software: you can redistribute it
* and/or modify it under the terms of version 3 of the
* GNU General Public License as published by the Free Software Foundation.
*
* Go For It! is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Go For It!. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_ABOUT_DIALOG (about_dialog_get_type ())
#define ABOUT_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ABOUT_DIALOG, AboutDialog))
#define ABOUT_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ABOUT_DIALOG, AboutDialogClass))
#define IS_ABOUT_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ABOUT_DIALOG))
#define IS_ABOUT_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ABOUT_DIALOG))
#define ABOUT_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ABOUT_DIALOG, AboutDialogClass))

typedef struct _AboutDialog AboutDialog;
typedef struct _AboutDialogClass AboutDialogClass;
typedef struct _AboutDialogPrivate AboutDialogPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _AboutDialog {
	GtkAboutDialog parent_instance;
	AboutDialogPrivate * priv;
};

struct _AboutDialogClass {
	GtkAboutDialogClass parent_class;
};


static gpointer about_dialog_parent_class = NULL;

GType about_dialog_get_type (void) G_GNUC_CONST;
enum  {
	ABOUT_DIALOG_DUMMY_PROPERTY
};
AboutDialog* about_dialog_new (GtkWindow* parent);
AboutDialog* about_dialog_construct (GType object_type, GtkWindow* parent);
static void about_dialog_setup_content (AboutDialog* self);
static void about_dialog_response_handler (AboutDialog* self, gint response);
static void _about_dialog_response_handler_gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
#define GOFI_ICON_NAME "com.github.jmoerman.go-for-it"
#define GOFI_PROJECT_WEBSITE "http://manuel-kehl.de/projects/go-for-it/"
#define GOFI_APP_VERSION "1.6.10"
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void _about_dialog_response_handler_gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
#line 31 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	about_dialog_response_handler ((AboutDialog*) self, response_id);
#line 73 "AboutDialog.c"
}


AboutDialog* about_dialog_construct (GType object_type, GtkWindow* parent) {
	AboutDialog * self = NULL;
	GtkWindow* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
#line 22 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	self = (AboutDialog*) g_object_new (object_type, NULL);
#line 23 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp0_ = parent;
#line 23 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_window_set_transient_for ((GtkWindow*) self, _tmp0_);
#line 25 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_window_set_default_size ((GtkWindow*) self, 450, 500);
#line 26 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp1_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) self);
#line 26 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	g_object_set ((GtkWidget*) _tmp1_, "margin", 10, NULL);
#line 27 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp2_ = _ ("About");
#line 27 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp3_ = g_strconcat (_tmp2_, " Go For It!", NULL);
#line 27 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp4_ = _tmp3_;
#line 27 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_window_set_title ((GtkWindow*) self, _tmp4_);
#line 27 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_g_free0 (_tmp4_);
#line 28 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	about_dialog_setup_content (self);
#line 31 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	g_signal_connect_object ((GtkDialog*) self, "response", (GCallback) _about_dialog_response_handler_gtk_dialog_response, self, 0);
#line 22 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	return self;
#line 112 "AboutDialog.c"
}


AboutDialog* about_dialog_new (GtkWindow* parent) {
#line 22 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	return about_dialog_construct (TYPE_ABOUT_DIALOG, parent);
#line 119 "AboutDialog.c"
}


/**
     * Displays a welcome message with basic information about Go For It!
     */
static void about_dialog_setup_content (AboutDialog* self) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gchar** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	gchar* _tmp5_ = NULL;
	gchar** _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
#line 37 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	g_return_if_fail (self != NULL);
#line 38 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_about_dialog_set_program_name ((GtkAboutDialog*) self, "Go For It!");
#line 39 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_about_dialog_set_logo_icon_name ((GtkAboutDialog*) self, GOFI_ICON_NAME);
#line 41 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp0_ = _ ("A stylish to-do list with built-in productivity timer.");
#line 41 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_about_dialog_set_comments ((GtkAboutDialog*) self, _tmp0_);
#line 42 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_about_dialog_set_website ((GtkAboutDialog*) self, GOFI_PROJECT_WEBSITE);
#line 43 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_about_dialog_set_version ((GtkAboutDialog*) self, GOFI_APP_VERSION);
#line 45 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_about_dialog_set_license_type ((GtkAboutDialog*) self, GTK_LICENSE_GPL_3_0);
#line 47 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp1_ = g_strdup ("Jonathan Moerman");
#line 47 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp2_ = g_strdup ("<a href='http://manuel-kehl.de'>Manuel Kehl</a>");
#line 47 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp3_ = g_new0 (gchar*, 2 + 1);
#line 47 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp3_[0] = _tmp1_;
#line 47 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp3_[1] = _tmp2_;
#line 47 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp4_ = _tmp3_;
#line 47 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp4__length1 = 2;
#line 47 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_about_dialog_set_authors ((GtkAboutDialog*) self, _tmp4_);
#line 47 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp4_ = (_vala_array_free (_tmp4_, _tmp4__length1, (GDestroyNotify) g_free), NULL);
#line 51 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp5_ = g_strdup ("<a href='http://traumad91.deviantart.com'>Micah Ilbery</a>");
#line 51 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp6_ = g_new0 (gchar*, 1 + 1);
#line 51 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp6_[0] = _tmp5_;
#line 51 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp7_ = _tmp6_;
#line 51 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp7__length1 = 1;
#line 51 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	gtk_about_dialog_set_artists ((GtkAboutDialog*) self, _tmp7_);
#line 51 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp7_ = (_vala_array_free (_tmp7_, _tmp7__length1, (GDestroyNotify) g_free), NULL);
#line 185 "AboutDialog.c"
}


static void about_dialog_response_handler (AboutDialog* self, gint response) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gint _tmp2_ = 0;
#line 54 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	g_return_if_fail (self != NULL);
#line 55 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	_tmp2_ = response;
#line 55 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	if (_tmp2_ == ((gint) GTK_RESPONSE_DELETE_EVENT)) {
#line 55 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
		_tmp1_ = TRUE;
#line 201 "AboutDialog.c"
	} else {
		gint _tmp3_ = 0;
#line 56 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
		_tmp3_ = response;
#line 56 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
		_tmp1_ = _tmp3_ == ((gint) GTK_RESPONSE_CANCEL);
#line 208 "AboutDialog.c"
	}
#line 55 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	if (_tmp1_) {
#line 55 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
		_tmp0_ = TRUE;
#line 214 "AboutDialog.c"
	} else {
		gint _tmp4_ = 0;
#line 57 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
		_tmp4_ = response;
#line 57 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
		_tmp0_ = _tmp4_ == ((gint) GTK_RESPONSE_CLOSE);
#line 221 "AboutDialog.c"
	}
#line 55 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	if (_tmp0_) {
#line 58 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
		gtk_widget_destroy ((GtkWidget*) self);
#line 227 "AboutDialog.c"
	}
}


static void about_dialog_class_init (AboutDialogClass * klass) {
#line 21 "/home/mark/projects/Go-For-It/src/view/AboutDialog.vala"
	about_dialog_parent_class = g_type_class_peek_parent (klass);
#line 235 "AboutDialog.c"
}


static void about_dialog_instance_init (AboutDialog * self) {
}


/**
 * A dialog for displaying information about this application.
 */
GType about_dialog_get_type (void) {
	static volatile gsize about_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&about_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AboutDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) about_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AboutDialog), 0, (GInstanceInitFunc) about_dialog_instance_init, NULL };
		GType about_dialog_type_id;
		about_dialog_type_id = g_type_register_static (gtk_about_dialog_get_type (), "AboutDialog", &g_define_type_info, 0);
		g_once_init_leave (&about_dialog_type_id__volatile, about_dialog_type_id);
	}
	return about_dialog_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



