/* ContributeDialog.c generated by valac 0.34.7, the Vala compiler
 * generated from ContributeDialog.vala, do not modify */

/* Copyright 2014-2017 Go For It! developers
*
* This file is part of Go For It!.
*
* Go For It! is free software: you can redistribute it
* and/or modify it under the terms of version 3 of the
* GNU General Public License as published by the Free Software Foundation.
*
* Go For It! is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Go For It!. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_CONTRIBUTE_DIALOG (contribute_dialog_get_type ())
#define CONTRIBUTE_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CONTRIBUTE_DIALOG, ContributeDialog))
#define CONTRIBUTE_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CONTRIBUTE_DIALOG, ContributeDialogClass))
#define IS_CONTRIBUTE_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CONTRIBUTE_DIALOG))
#define IS_CONTRIBUTE_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CONTRIBUTE_DIALOG))
#define CONTRIBUTE_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CONTRIBUTE_DIALOG, ContributeDialogClass))

typedef struct _ContributeDialog ContributeDialog;
typedef struct _ContributeDialogClass ContributeDialogClass;
typedef struct _ContributeDialogPrivate ContributeDialogPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ContributeDialog {
	GtkMessageDialog parent_instance;
	ContributeDialogPrivate * priv;
};

struct _ContributeDialogClass {
	GtkMessageDialogClass parent_class;
};


static gpointer contribute_dialog_parent_class = NULL;

GType contribute_dialog_get_type (void) G_GNUC_CONST;
enum  {
	CONTRIBUTE_DIALOG_DUMMY_PROPERTY
};
ContributeDialog* contribute_dialog_new (GtkWindow* parent);
ContributeDialog* contribute_dialog_construct (GType object_type, GtkWindow* parent);
#define GOFI_PROJECT_REPO "https://github.com/JMoerman/Go-For-It"
#define GOFI_PROJECT_DONATIONS "https://jmoerman.github.io/donate/"
static void __lambda33_ (ContributeDialog* self, gint e);
static void ___lambda33__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);


static void __lambda33_ (ContributeDialog* self, gint e) {
#line 43 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 69 "ContributeDialog.c"
}


static void ___lambda33__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
#line 42 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	__lambda33_ ((ContributeDialog*) self, response_id);
#line 76 "ContributeDialog.c"
}


ContributeDialog* contribute_dialog_construct (GType object_type, GtkWindow* parent) {
	ContributeDialog * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	gchar* _tmp36_ = NULL;
	gchar* _tmp37_ = NULL;
	GtkWidget* _tmp38_ = NULL;
	GtkWidget* _tmp39_ = NULL;
	GtkWindow* _tmp40_ = NULL;
#line 25 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	self = (ContributeDialog*) g_object_new (object_type, "buttons", GTK_BUTTONS_OK, NULL);
#line 26 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	g_object_set ((GtkMessageDialog*) self, "message-type", GTK_MESSAGE_INFO, NULL);
#line 27 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	gtk_window_set_modal ((GtkWindow*) self, TRUE);
#line 28 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp0_ = _ ("Contributions and Donations");
#line 28 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	gtk_window_set_title ((GtkWindow*) self, _tmp0_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp1_ = _ ("Thank you for supporting");
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp2_ = g_strconcat ("<b>", _tmp1_, NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp3_ = _tmp2_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp4_ = g_strconcat (_tmp3_, " <i>Go For It!</i>\n\n\n</b>", NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp5_ = _tmp4_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp6_ = _ ("Submitting code, artwork, translations or documentation is a great way" \
" of contributing to the project:");
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp7_ = g_strconcat (_tmp5_, _tmp6_, NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp8_ = _tmp7_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp9_ = g_strconcat (_tmp8_, "\n\n", NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp10_ = _tmp9_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp11_ = g_strconcat (_tmp10_, "<a href=\"", NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp12_ = _tmp11_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp13_ = g_strconcat (_tmp12_, GOFI_PROJECT_REPO, NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp14_ = _tmp13_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp15_ = g_strconcat (_tmp14_, "\">", NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp16_ = _tmp15_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp17_ = g_strconcat (_tmp16_, GOFI_PROJECT_REPO, NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp18_ = _tmp17_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp19_ = g_strconcat (_tmp18_, "</a>", NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp20_ = _tmp19_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp21_ = g_strconcat (_tmp20_, "\n\n\n", NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp22_ = _tmp21_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp23_ = _ ("If you really like this app, you can buy me a drink:");
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp24_ = g_strconcat (_tmp22_, _tmp23_, NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp25_ = _tmp24_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp26_ = g_strconcat (_tmp25_, "\n\n", NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp27_ = _tmp26_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp28_ = g_strconcat (_tmp27_, "<a href=\"", NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp29_ = _tmp28_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp30_ = g_strconcat (_tmp29_, GOFI_PROJECT_DONATIONS, NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp31_ = _tmp30_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp32_ = g_strconcat (_tmp31_, "\">", NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp33_ = _tmp32_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp34_ = g_strconcat (_tmp33_, GOFI_PROJECT_DONATIONS, NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp35_ = _tmp34_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp36_ = g_strconcat (_tmp35_, "</a>", NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp37_ = _tmp36_;
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	gtk_message_dialog_format_secondary_markup ((GtkMessageDialog*) self, "%s", _tmp37_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp37_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp35_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp33_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp31_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp29_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp27_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp25_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp22_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp20_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp18_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp16_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp14_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp12_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp10_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp8_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp5_);
#line 30 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_g_free0 (_tmp3_);
#line 42 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	g_signal_connect_object ((GtkDialog*) self, "response", (GCallback) ___lambda33__gtk_dialog_response, self, 0);
#line 46 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp38_ = gtk_dialog_get_action_area ((GtkDialog*) self);
#line 46 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	gtk_widget_set_hexpand (_tmp38_, FALSE);
#line 47 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp39_ = gtk_dialog_get_action_area ((GtkDialog*) self);
#line 47 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	gtk_widget_set_halign (_tmp39_, GTK_ALIGN_END);
#line 48 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	_tmp40_ = parent;
#line 48 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	gtk_window_set_transient_for ((GtkWindow*) self, _tmp40_);
#line 24 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	return self;
#line 259 "ContributeDialog.c"
}


ContributeDialog* contribute_dialog_new (GtkWindow* parent) {
#line 24 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	return contribute_dialog_construct (TYPE_CONTRIBUTE_DIALOG, parent);
#line 266 "ContributeDialog.c"
}


static void contribute_dialog_class_init (ContributeDialogClass * klass) {
#line 22 "/home/mark/projects/Go-For-It/src/view/ContributeDialog.vala"
	contribute_dialog_parent_class = g_type_class_peek_parent (klass);
#line 273 "ContributeDialog.c"
}


static void contribute_dialog_instance_init (ContributeDialog * self) {
}


/**
 * A dialog that displays information about how to support the project.
 */
GType contribute_dialog_get_type (void) {
	static volatile gsize contribute_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&contribute_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ContributeDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) contribute_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ContributeDialog), 0, (GInstanceInitFunc) contribute_dialog_instance_init, NULL };
		GType contribute_dialog_type_id;
		contribute_dialog_type_id = g_type_register_static (gtk_message_dialog_get_type (), "ContributeDialog", &g_define_type_info, 0);
		g_once_init_leave (&contribute_dialog_type_id__volatile, contribute_dialog_type_id);
	}
	return contribute_dialog_type_id__volatile;
}



