/* TaskList.c generated by valac 0.34.7, the Vala compiler
 * generated from TaskList.vala, do not modify */

/* Copyright 2014-2017 Go For It! developers
*
* This file is part of Go For It!.
*
* Go For It! is free software: you can redistribute it
* and/or modify it under the terms of version 3 of the
* GNU General Public License as published by the Free Software Foundation.
*
* Go For It! is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Go For It!. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>


#define TYPE_TASK_LIST (task_list_get_type ())
#define TASK_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TASK_LIST, TaskList))
#define TASK_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TASK_LIST, TaskListClass))
#define IS_TASK_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TASK_LIST))
#define IS_TASK_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TASK_LIST))
#define TASK_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TASK_LIST, TaskListClass))

typedef struct _TaskList TaskList;
typedef struct _TaskListClass TaskListClass;
typedef struct _TaskListPrivate TaskListPrivate;

#define TYPE_DRAG_LIST (drag_list_get_type ())
#define DRAG_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DRAG_LIST, DragList))
#define DRAG_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DRAG_LIST, DragListClass))
#define IS_DRAG_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DRAG_LIST))
#define IS_DRAG_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DRAG_LIST))
#define DRAG_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DRAG_LIST, DragListClass))

typedef struct _DragList DragList;
typedef struct _DragListClass DragListClass;

#define TYPE_FILTER (filter_get_type ())
#define FILTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FILTER, Filter))
#define FILTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FILTER, FilterClass))
#define IS_FILTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FILTER))
#define IS_FILTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FILTER))
#define FILTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FILTER, FilterClass))

typedef struct _Filter Filter;
typedef struct _FilterClass FilterClass;

#define TYPE_TASK_STORE (task_store_get_type ())
#define TASK_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TASK_STORE, TaskStore))
#define TASK_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TASK_STORE, TaskStoreClass))
#define IS_TASK_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TASK_STORE))
#define IS_TASK_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TASK_STORE))
#define TASK_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TASK_STORE, TaskStoreClass))

typedef struct _TaskStore TaskStore;
typedef struct _TaskStoreClass TaskStoreClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _filter_unref0(var) ((var == NULL) ? NULL : (var = (filter_unref (var), NULL)))

#define TYPE_TODO_TASK (todo_task_get_type ())
#define TODO_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TODO_TASK, TodoTask))
#define TODO_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TODO_TASK, TodoTaskClass))
#define IS_TODO_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TODO_TASK))
#define IS_TODO_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TODO_TASK))
#define TODO_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TODO_TASK, TodoTaskClass))

typedef struct _TodoTask TodoTask;
typedef struct _TodoTaskClass TodoTaskClass;

#define TYPE_DRAG_LIST_ROW (drag_list_row_get_type ())
#define DRAG_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DRAG_LIST_ROW, DragListRow))
#define DRAG_LIST_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DRAG_LIST_ROW, DragListRowClass))
#define IS_DRAG_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DRAG_LIST_ROW))
#define IS_DRAG_LIST_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DRAG_LIST_ROW))
#define DRAG_LIST_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DRAG_LIST_ROW, DragListRowClass))

typedef struct _DragListRow DragListRow;
typedef struct _DragListRowClass DragListRowClass;

#define TYPE_TASK_ROW (task_row_get_type ())
#define TASK_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TASK_ROW, TaskRow))
#define TASK_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TASK_ROW, TaskRowClass))
#define IS_TASK_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TASK_ROW))
#define IS_TASK_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TASK_ROW))
#define TASK_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TASK_ROW, TaskRowClass))

typedef struct _TaskRow TaskRow;
typedef struct _TaskRowClass TaskRowClass;

#define TYPE_DRAG_LIST_MODEL (drag_list_model_get_type ())
#define DRAG_LIST_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DRAG_LIST_MODEL, DragListModel))
#define IS_DRAG_LIST_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DRAG_LIST_MODEL))
#define DRAG_LIST_MODEL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_DRAG_LIST_MODEL, DragListModelIface))

typedef struct _DragListModel DragListModel;
typedef struct _DragListModelIface DragListModelIface;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _TaskList {
	GtkGrid parent_instance;
	TaskListPrivate * priv;
};

struct _TaskListClass {
	GtkGridClass parent_class;
};

struct _TaskListPrivate {
	GtkScrolledWindow* scroll_view;
	DragList* task_view;
	GtkGrid* add_new_grid;
	GtkSearchBar* search_bar;
	GtkEntry* add_new_txt;
	GtkSearchEntry* filter_entry;
	Filter* filter;
	TaskStore* model;
};

struct _DragListModelIface {
	GTypeInterface parent_iface;
	void (*move_item) (DragListModel* self, guint old_position, guint new_position);
	GObject* (*get_item) (DragListModel* self, guint position);
	GType (*get_item_type) (DragListModel* self);
	guint (*get_n_items) (DragListModel* self);
};

typedef GtkWidget* (*DragListCreateWidgetFunc) (GObject* item, void* user_data);
typedef gboolean (*DragListFilterFunc) (DragListRow* row, void* user_data);

static gpointer task_list_parent_class = NULL;

GType task_list_get_type (void) G_GNUC_CONST;
GType drag_list_get_type (void) G_GNUC_CONST;
gpointer filter_ref (gpointer instance);
void filter_unref (gpointer instance);
GParamSpec* param_spec_filter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_filter (GValue* value, gpointer v_object);
void value_take_filter (GValue* value, gpointer v_object);
gpointer value_get_filter (const GValue* value);
GType filter_get_type (void) G_GNUC_CONST;
GType task_store_get_type (void) G_GNUC_CONST;
#define TASK_LIST_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TASK_LIST, TaskListPrivate))
enum  {
	TASK_LIST_DUMMY_PROPERTY
};
TaskList* task_list_new (TaskStore* model, gboolean add_new);
TaskList* task_list_construct (GType object_type, TaskStore* model, gboolean add_new);
static void task_list_setup_filter (TaskList* self);
static void task_list_setup_task_view (TaskList* self);
static void task_list_setup_add_new (TaskList* self);
GType todo_task_get_type (void) G_GNUC_CONST;
TodoTask* task_list_get_selected_task (TaskList* self);
GType drag_list_row_get_type (void) G_GNUC_CONST;
GType task_row_get_type (void) G_GNUC_CONST;
DragListRow* drag_list_get_selected_row (DragList* self);
TodoTask* task_row_get_task (TaskRow* self);
static GtkWidget* task_list_create_row (TaskList* self, GObject* task);
TaskRow* task_row_new (TodoTask* task);
TaskRow* task_row_construct (GType object_type, TodoTask* task);
static void task_list_on_row_link_clicked (TaskList* self, const gchar* uri);
static void _task_list_on_row_link_clicked_task_row_link_clicked (TaskRow* _sender, const gchar* uri, gpointer self);
static void task_list_on_deletion_requested (TaskList* self, TaskRow* row);
static void _task_list_on_deletion_requested_task_row_deletion_requested (TaskRow* _sender, gpointer self);
void task_store_remove_task (TaskStore* self, TodoTask* task);
DragList* drag_list_new (void);
DragList* drag_list_construct (GType object_type);
GType drag_list_model_get_type (void) G_GNUC_CONST;
void drag_list_bind_model (DragList* self, DragListModel* model, DragListCreateWidgetFunc create_widget_func, void* create_widget_func_target, GDestroyNotify create_widget_func_target_destroy_notify);
static GtkWidget* _task_list_create_row_drag_list_create_widget_func (GObject* item, gpointer self);
void drag_list_set_vadjustment (DragList* self, GtkAdjustment* value);
static void task_list_on_task_view_row_selected (TaskList* self, DragListRow* selected_row);
static void _task_list_on_task_view_row_selected_drag_list_row_selected (DragList* _sender, DragListRow* row, gpointer self);
static void task_list_on_task_view_row_activated (TaskList* self, DragListRow* selected_row);
static void _task_list_on_task_view_row_activated_drag_list_row_activated (DragList* _sender, DragListRow* row, gpointer self);
void drag_list_set_filter_func (DragList* self, DragListFilterFunc filter_func, void* filter_func_target);
gboolean filter_filter (Filter* self, DragListRow* _row);
static gboolean _filter_filter_drag_list_filter_func (DragListRow* row, gpointer self);
void task_row_edit (TaskRow* self);
static void __lambda17_ (TaskList* self, GtkEntryIconPosition pos, GdkEvent* event);
static void ___lambda17__gtk_entry_icon_press (GtkEntry* _sender, GtkEntryIconPosition p0, GdkEvent* p1, gpointer self);
static void __lambda18_ (TaskList* self, GtkEntry* source);
static void ___lambda18__gtk_entry_activate (GtkEntry* _sender, gpointer self);
Filter* filter_new (void);
Filter* filter_construct (GType object_type);
static void __lambda16_ (TaskList* self);
void filter_parse (Filter* self, const gchar* filter_string);
void drag_list_invalidate_filter (DragList* self);
static void ___lambda16__gtk_search_entry_search_changed (GtkSearchEntry* _sender, gpointer self);
void task_list_toggle_filter_bar (TaskList* self);
static void task_list_finalize (GObject* obj);


/**
     * Constructor of the TaskList class.
     * @param add_new whether or not to show a textfield for adding new entries
     */
static gpointer _g_object_ref0 (gpointer self) {
#line 46 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	return self ? g_object_ref (self) : NULL;
#line 214 "TaskList.c"
}


TaskList* task_list_construct (GType object_type, TaskStore* model, gboolean add_new) {
	TaskList * self = NULL;
	TaskStore* _tmp0_ = NULL;
	TaskStore* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
#line 42 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_val_if_fail (model != NULL, NULL);
#line 42 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self = (TaskList*) g_object_new (object_type, NULL);
#line 44 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_VERTICAL);
#line 45 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_set ((GtkWidget*) self, "expand", TRUE, NULL);
#line 46 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = model;
#line 46 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 46 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->model);
#line 46 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self->priv->model = _tmp1_;
#line 49 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	task_list_setup_filter (self);
#line 50 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	task_list_setup_task_view (self);
#line 51 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp2_ = add_new;
#line 51 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	if (_tmp2_) {
#line 52 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		task_list_setup_add_new (self);
#line 249 "TaskList.c"
	}
#line 42 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	return self;
#line 253 "TaskList.c"
}


TaskList* task_list_new (TaskStore* model, gboolean add_new) {
#line 42 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	return task_list_construct (TYPE_TASK_LIST, model, add_new);
#line 260 "TaskList.c"
}


TodoTask* task_list_get_selected_task (TaskList* self) {
	TodoTask* result = NULL;
	TaskRow* selected_row = NULL;
	DragList* _tmp0_ = NULL;
	DragListRow* _tmp1_ = NULL;
	TaskRow* _tmp2_ = NULL;
	TaskRow* _tmp3_ = NULL;
#line 56 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 57 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = self->priv->task_view;
#line 57 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = drag_list_get_selected_row (_tmp0_);
#line 57 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, TYPE_TASK_ROW, TaskRow));
#line 57 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	selected_row = _tmp2_;
#line 58 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp3_ = selected_row;
#line 58 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	if (_tmp3_ != NULL) {
#line 285 "TaskList.c"
		TaskRow* _tmp4_ = NULL;
		TodoTask* _tmp5_ = NULL;
		TodoTask* _tmp6_ = NULL;
		TodoTask* _tmp7_ = NULL;
#line 59 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp4_ = selected_row;
#line 59 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp5_ = task_row_get_task (_tmp4_);
#line 59 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp6_ = _tmp5_;
#line 59 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp7_ = _g_object_ref0 (_tmp6_);
#line 59 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		result = _tmp7_;
#line 59 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_g_object_unref0 (selected_row);
#line 59 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		return result;
#line 304 "TaskList.c"
	}
#line 61 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	result = NULL;
#line 61 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (selected_row);
#line 61 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	return result;
#line 312 "TaskList.c"
}


static void _task_list_on_row_link_clicked_task_row_link_clicked (TaskRow* _sender, const gchar* uri, gpointer self) {
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	task_list_on_row_link_clicked ((TaskList*) self, uri);
#line 319 "TaskList.c"
}


static void _task_list_on_deletion_requested_task_row_deletion_requested (TaskRow* _sender, gpointer self) {
#line 67 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	task_list_on_deletion_requested ((TaskList*) self, _sender);
#line 326 "TaskList.c"
}


static GtkWidget* task_list_create_row (TaskList* self, GObject* task) {
	GtkWidget* result = NULL;
	TaskRow* row = NULL;
	GObject* _tmp0_ = NULL;
	TaskRow* _tmp1_ = NULL;
#line 64 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 64 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_val_if_fail (task != NULL, NULL);
#line 65 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = task;
#line 65 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = task_row_new (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, TYPE_TODO_TASK, TodoTask));
#line 65 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_ref_sink (_tmp1_);
#line 65 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	row = _tmp1_;
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_connect_object (row, "link-clicked", (GCallback) _task_list_on_row_link_clicked_task_row_link_clicked, self, 0);
#line 67 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_connect_object (row, "deletion-requested", (GCallback) _task_list_on_deletion_requested_task_row_deletion_requested, self, 0);
#line 68 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	result = (GtkWidget*) row;
#line 68 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	return result;
#line 355 "TaskList.c"
}


static void task_list_on_row_link_clicked (TaskList* self, const gchar* uri) {
	GtkSearchBar* _tmp0_ = NULL;
	GtkSearchEntry* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
#line 71 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 71 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (uri != NULL);
#line 72 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = self->priv->search_bar;
#line 72 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_search_bar_set_search_mode (_tmp0_, TRUE);
#line 73 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = self->priv->filter_entry;
#line 73 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp2_ = uri;
#line 73 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_entry_set_text ((GtkEntry*) _tmp1_, _tmp2_);
#line 377 "TaskList.c"
}


static void task_list_on_deletion_requested (TaskList* self, TaskRow* row) {
	TaskStore* _tmp0_ = NULL;
	TaskRow* _tmp1_ = NULL;
	TodoTask* _tmp2_ = NULL;
	TodoTask* _tmp3_ = NULL;
#line 76 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 76 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (row != NULL);
#line 77 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = self->priv->model;
#line 77 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = row;
#line 77 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp2_ = task_row_get_task (_tmp1_);
#line 77 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp3_ = _tmp2_;
#line 77 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	task_store_remove_task (_tmp0_, _tmp3_);
#line 400 "TaskList.c"
}


/**
     * Configures the list to display the task entries.
     */
static GtkWidget* _task_list_create_row_drag_list_create_widget_func (GObject* item, gpointer self) {
	GtkWidget* result;
	result = task_list_create_row ((TaskList*) self, item);
#line 87 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	return result;
#line 412 "TaskList.c"
}


static void _task_list_on_task_view_row_selected_drag_list_row_selected (DragList* _sender, DragListRow* row, gpointer self) {
#line 89 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	task_list_on_task_view_row_selected ((TaskList*) self, row);
#line 419 "TaskList.c"
}


static void _task_list_on_task_view_row_activated_drag_list_row_activated (DragList* _sender, DragListRow* row, gpointer self) {
#line 90 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	task_list_on_task_view_row_activated ((TaskList*) self, row);
#line 426 "TaskList.c"
}


static gboolean _filter_filter_drag_list_filter_func (DragListRow* row, gpointer self) {
	gboolean result;
	result = filter_filter ((Filter*) self, row);
#line 91 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	return result;
#line 435 "TaskList.c"
}


static void task_list_setup_task_view (TaskList* self) {
	GtkScrolledWindow* _tmp0_ = NULL;
	DragList* _tmp1_ = NULL;
	DragList* _tmp2_ = NULL;
	TaskStore* _tmp3_ = NULL;
	DragList* _tmp4_ = NULL;
	GtkScrolledWindow* _tmp5_ = NULL;
	GtkAdjustment* _tmp6_ = NULL;
	GtkAdjustment* _tmp7_ = NULL;
	DragList* _tmp8_ = NULL;
	DragList* _tmp9_ = NULL;
	DragList* _tmp10_ = NULL;
	Filter* _tmp11_ = NULL;
	GtkScrolledWindow* _tmp12_ = NULL;
	GtkScrolledWindow* _tmp13_ = NULL;
	DragList* _tmp14_ = NULL;
	GtkScrolledWindow* _tmp15_ = NULL;
#line 83 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 84 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 84 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_ref_sink (_tmp0_);
#line 84 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->scroll_view);
#line 84 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self->priv->scroll_view = _tmp0_;
#line 85 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = drag_list_new ();
#line 85 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_ref_sink (_tmp1_);
#line 85 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->task_view);
#line 85 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self->priv->task_view = _tmp1_;
#line 87 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp2_ = self->priv->task_view;
#line 87 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp3_ = self->priv->model;
#line 87 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	drag_list_bind_model (_tmp2_, G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, TYPE_DRAG_LIST_MODEL, DragListModel), _task_list_create_row_drag_list_create_widget_func, g_object_ref (self), g_object_unref);
#line 88 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp4_ = self->priv->task_view;
#line 88 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp5_ = self->priv->scroll_view;
#line 88 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp6_ = gtk_scrolled_window_get_vadjustment (_tmp5_);
#line 88 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp7_ = _tmp6_;
#line 88 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	drag_list_set_vadjustment (_tmp4_, _tmp7_);
#line 89 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp8_ = self->priv->task_view;
#line 89 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_connect_object (_tmp8_, "row-selected", (GCallback) _task_list_on_task_view_row_selected_drag_list_row_selected, self, 0);
#line 90 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp9_ = self->priv->task_view;
#line 90 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_connect_object (_tmp9_, "row-activated", (GCallback) _task_list_on_task_view_row_activated_drag_list_row_activated, self, 0);
#line 91 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp10_ = self->priv->task_view;
#line 91 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp11_ = self->priv->filter;
#line 91 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	drag_list_set_filter_func (_tmp10_, _filter_filter_drag_list_filter_func, _tmp11_);
#line 93 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp12_ = self->priv->scroll_view;
#line 93 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_set ((GtkWidget*) _tmp12_, "expand", TRUE, NULL);
#line 96 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp13_ = self->priv->scroll_view;
#line 96 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp14_ = self->priv->task_view;
#line 96 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_container_add ((GtkContainer*) _tmp13_, (GtkWidget*) _tmp14_);
#line 97 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp15_ = self->priv->scroll_view;
#line 97 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp15_);
#line 518 "TaskList.c"
}


static void task_list_on_task_view_row_selected (TaskList* self, DragListRow* selected_row) {
	TodoTask* task = NULL;
	DragListRow* _tmp0_ = NULL;
	TodoTask* _tmp5_ = NULL;
#line 100 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 101 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	task = NULL;
#line 102 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = selected_row;
#line 102 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	if (_tmp0_ != NULL) {
#line 534 "TaskList.c"
		DragListRow* _tmp1_ = NULL;
		TodoTask* _tmp2_ = NULL;
		TodoTask* _tmp3_ = NULL;
		TodoTask* _tmp4_ = NULL;
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp1_ = selected_row;
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp2_ = task_row_get_task (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, TYPE_TASK_ROW, TaskRow));
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp3_ = _tmp2_;
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp4_ = _g_object_ref0 (_tmp3_);
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_g_object_unref0 (task);
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		task = _tmp4_;
#line 551 "TaskList.c"
	}
#line 105 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp5_ = task;
#line 105 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_emit_by_name (self, "selection-changed", _tmp5_);
#line 100 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (task);
#line 559 "TaskList.c"
}


static void task_list_on_task_view_row_activated (TaskList* self, DragListRow* selected_row) {
	DragListRow* _tmp0_ = NULL;
#line 108 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 109 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = selected_row;
#line 109 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	task_row_edit (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, TYPE_TASK_ROW, TaskRow));
#line 571 "TaskList.c"
}


/**
     * Configures the container with the "add new task" text entry.
     */
static void __lambda17_ (TaskList* self, GtkEntryIconPosition pos, GdkEvent* event) {
	GtkEntryIconPosition _tmp0_ = 0;
#line 129 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (event != NULL);
#line 130 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = pos;
#line 130 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	if (_tmp0_ == GTK_ENTRY_ICON_SECONDARY) {
#line 586 "TaskList.c"
		GtkEntry* _tmp1_ = NULL;
		const gchar* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		GtkEntry* _tmp4_ = NULL;
#line 132 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp1_ = self->priv->add_new_txt;
#line 132 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp2_ = gtk_entry_get_text (_tmp1_);
#line 132 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp3_ = _tmp2_;
#line 132 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		g_signal_emit_by_name (self, "add-new-task", _tmp3_);
#line 133 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		_tmp4_ = self->priv->add_new_txt;
#line 133 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
		gtk_entry_set_text (_tmp4_, "");
#line 603 "TaskList.c"
	}
}


static void ___lambda17__gtk_entry_icon_press (GtkEntry* _sender, GtkEntryIconPosition p0, GdkEvent* p1, gpointer self) {
#line 129 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	__lambda17_ ((TaskList*) self, p0, p1);
#line 611 "TaskList.c"
}


static void __lambda18_ (TaskList* self, GtkEntry* source) {
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GtkEntry* _tmp3_ = NULL;
#line 137 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (source != NULL);
#line 138 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = self->priv->add_new_txt;
#line 138 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = gtk_entry_get_text (_tmp0_);
#line 138 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp2_ = _tmp1_;
#line 138 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_emit_by_name (self, "add-new-task", _tmp2_);
#line 139 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp3_ = self->priv->add_new_txt;
#line 139 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_entry_set_text (_tmp3_, "");
#line 634 "TaskList.c"
}


static void ___lambda18__gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 137 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	__lambda18_ ((TaskList*) self, _sender);
#line 641 "TaskList.c"
}


static void task_list_setup_add_new (TaskList* self) {
	GtkGrid* _tmp0_ = NULL;
	GtkGrid* _tmp1_ = NULL;
	GtkEntry* _tmp2_ = NULL;
	GtkEntry* _tmp3_ = NULL;
	GtkEntry* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	GtkEntry* _tmp8_ = NULL;
	GtkEntry* _tmp9_ = NULL;
	GtkEntry* _tmp10_ = NULL;
	GtkEntry* _tmp11_ = NULL;
	GtkGrid* _tmp12_ = NULL;
	GtkEntry* _tmp13_ = NULL;
	GtkGrid* _tmp14_ = NULL;
#line 115 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 116 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = (GtkGrid*) gtk_grid_new ();
#line 116 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_ref_sink (_tmp0_);
#line 116 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->add_new_grid);
#line 116 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self->priv->add_new_grid = _tmp0_;
#line 117 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = self->priv->add_new_grid;
#line 117 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_orientable_set_orientation ((GtkOrientable*) _tmp1_, GTK_ORIENTATION_HORIZONTAL);
#line 119 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp2_ = (GtkEntry*) gtk_entry_new ();
#line 119 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_ref_sink (_tmp2_);
#line 119 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->add_new_txt);
#line 119 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self->priv->add_new_txt = _tmp2_;
#line 120 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp3_ = self->priv->add_new_txt;
#line 120 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp3_, TRUE);
#line 121 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp4_ = self->priv->add_new_txt;
#line 121 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp5_ = _ ("Add new task");
#line 121 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp6_ = g_strconcat (_tmp5_, "…", NULL);
#line 121 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp7_ = _tmp6_;
#line 121 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_entry_set_placeholder_text (_tmp4_, _tmp7_);
#line 121 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_free0 (_tmp7_);
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp8_ = self->priv->add_new_txt;
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_set ((GtkWidget*) _tmp8_, "margin", 5, NULL);
#line 124 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp9_ = self->priv->add_new_txt;
#line 124 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_entry_set_icon_from_icon_name (_tmp9_, GTK_ENTRY_ICON_SECONDARY, "list-add-symbolic");
#line 129 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp10_ = self->priv->add_new_txt;
#line 129 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_connect_object (_tmp10_, "icon-press", (GCallback) ___lambda17__gtk_entry_icon_press, self, 0);
#line 137 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp11_ = self->priv->add_new_txt;
#line 137 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_connect_object (_tmp11_, "activate", (GCallback) ___lambda18__gtk_entry_activate, self, 0);
#line 142 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp12_ = self->priv->add_new_grid;
#line 142 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp13_ = self->priv->add_new_txt;
#line 142 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_container_add ((GtkContainer*) _tmp12_, (GtkWidget*) _tmp13_);
#line 145 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp14_ = self->priv->add_new_grid;
#line 145 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp14_);
#line 725 "TaskList.c"
}


static void __lambda16_ (TaskList* self) {
	Filter* _tmp0_ = NULL;
	GtkSearchEntry* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	DragList* _tmp4_ = NULL;
#line 154 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = self->priv->filter;
#line 154 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = self->priv->filter_entry;
#line 154 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp2_ = gtk_entry_get_text ((GtkEntry*) _tmp1_);
#line 154 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp3_ = _tmp2_;
#line 154 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	filter_parse (_tmp0_, _tmp3_);
#line 155 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp4_ = self->priv->task_view;
#line 155 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	drag_list_invalidate_filter (_tmp4_);
#line 749 "TaskList.c"
}


static void ___lambda16__gtk_search_entry_search_changed (GtkSearchEntry* _sender, gpointer self) {
#line 153 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	__lambda16_ ((TaskList*) self);
#line 756 "TaskList.c"
}


static void task_list_setup_filter (TaskList* self) {
	GtkSearchBar* _tmp0_ = NULL;
	GtkSearchEntry* _tmp1_ = NULL;
	Filter* _tmp2_ = NULL;
	GtkSearchEntry* _tmp3_ = NULL;
	GtkSearchBar* _tmp4_ = NULL;
	GtkSearchEntry* _tmp5_ = NULL;
	GtkSearchBar* _tmp6_ = NULL;
	GtkSearchBar* _tmp7_ = NULL;
#line 148 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = (GtkSearchBar*) gtk_search_bar_new ();
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_ref_sink (_tmp0_);
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->search_bar);
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self->priv->search_bar = _tmp0_;
#line 150 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = (GtkSearchEntry*) gtk_search_entry_new ();
#line 150 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_ref_sink (_tmp1_);
#line 150 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->filter_entry);
#line 150 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self->priv->filter_entry = _tmp1_;
#line 151 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp2_ = filter_new ();
#line 151 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_filter_unref0 (self->priv->filter);
#line 151 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self->priv->filter = _tmp2_;
#line 153 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp3_ = self->priv->filter_entry;
#line 153 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_connect_object (_tmp3_, "search-changed", (GCallback) ___lambda16__gtk_search_entry_search_changed, self, 0);
#line 158 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp4_ = self->priv->search_bar;
#line 158 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp5_ = self->priv->filter_entry;
#line 158 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_container_add ((GtkContainer*) _tmp4_, (GtkWidget*) _tmp5_);
#line 159 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp6_ = self->priv->search_bar;
#line 159 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_search_bar_set_show_close_button (_tmp6_, TRUE);
#line 161 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp7_ = self->priv->search_bar;
#line 161 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp7_);
#line 811 "TaskList.c"
}


void task_list_toggle_filter_bar (TaskList* self) {
	GtkSearchBar* _tmp0_ = NULL;
	GtkSearchBar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
#line 164 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_return_if_fail (self != NULL);
#line 165 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp0_ = self->priv->search_bar;
#line 165 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp1_ = self->priv->search_bar;
#line 165 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_object_get (_tmp1_, "search-mode-enabled", &_tmp2_, NULL);
#line 165 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_tmp3_ = _tmp2_;
#line 165 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	gtk_search_bar_set_search_mode (_tmp0_, !_tmp3_);
#line 832 "TaskList.c"
}


static void task_list_class_init (TaskListClass * klass) {
#line 21 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	task_list_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_type_class_add_private (klass, sizeof (TaskListPrivate));
#line 21 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	G_OBJECT_CLASS (klass)->finalize = task_list_finalize;
#line 21 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_new ("add_new_task", TYPE_TASK_LIST, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
#line 21 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	g_signal_new ("selection_changed", TYPE_TASK_LIST, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, TYPE_TODO_TASK);
#line 847 "TaskList.c"
}


static void task_list_instance_init (TaskList * self) {
#line 21 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self->priv = TASK_LIST_GET_PRIVATE (self);
#line 854 "TaskList.c"
}


static void task_list_finalize (GObject* obj) {
	TaskList * self;
#line 21 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TASK_LIST, TaskList);
#line 23 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->scroll_view);
#line 24 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->task_view);
#line 25 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->add_new_grid);
#line 26 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->search_bar);
#line 27 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->add_new_txt);
#line 28 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->filter_entry);
#line 29 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_filter_unref0 (self->priv->filter);
#line 32 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	_g_object_unref0 (self->priv->model);
#line 21 "/home/mark/projects/Go-For-It/src/view/TaskList.vala"
	G_OBJECT_CLASS (task_list_parent_class)->finalize (obj);
#line 880 "TaskList.c"
}


/**
 * A widget for displaying and manipulating task lists.
 */
GType task_list_get_type (void) {
	static volatile gsize task_list_type_id__volatile = 0;
	if (g_once_init_enter (&task_list_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TaskListClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) task_list_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TaskList), 0, (GInstanceInitFunc) task_list_instance_init, NULL };
		GType task_list_type_id;
		task_list_type_id = g_type_register_static (gtk_grid_get_type (), "TaskList", &g_define_type_info, 0);
		g_once_init_leave (&task_list_type_id__volatile, task_list_type_id);
	}
	return task_list_type_id__volatile;
}



