/* TaskRow.c generated by valac 0.34.7, the Vala compiler
 * generated from TaskRow.vala, do not modify */

/* Copyright 2017 Go For It! developers
*
* This file is part of Go For It!.
*
* Go For It! is free software: you can redistribute it
* and/or modify it under the terms of version 3 of the
* GNU General Public License as published by the Free Software Foundation.
*
* Go For It! is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Go For It!. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <pango/pango.h>
#include <glib/gi18n-lib.h>


#define TYPE_DRAG_LIST_ROW (drag_list_row_get_type ())
#define DRAG_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DRAG_LIST_ROW, DragListRow))
#define DRAG_LIST_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DRAG_LIST_ROW, DragListRowClass))
#define IS_DRAG_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DRAG_LIST_ROW))
#define IS_DRAG_LIST_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DRAG_LIST_ROW))
#define DRAG_LIST_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DRAG_LIST_ROW, DragListRowClass))

typedef struct _DragListRow DragListRow;
typedef struct _DragListRowClass DragListRowClass;
typedef struct _DragListRowPrivate DragListRowPrivate;

#define TYPE_TASK_ROW (task_row_get_type ())
#define TASK_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TASK_ROW, TaskRow))
#define TASK_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TASK_ROW, TaskRowClass))
#define IS_TASK_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TASK_ROW))
#define IS_TASK_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TASK_ROW))
#define TASK_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TASK_ROW, TaskRowClass))

typedef struct _TaskRow TaskRow;
typedef struct _TaskRowClass TaskRowClass;
typedef struct _TaskRowPrivate TaskRowPrivate;

#define TASK_ROW_TYPE_TASK_MARKUP_LABEL (task_row_task_markup_label_get_type ())
#define TASK_ROW_TASK_MARKUP_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TASK_ROW_TYPE_TASK_MARKUP_LABEL, TaskRowTaskMarkupLabel))
#define TASK_ROW_TASK_MARKUP_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TASK_ROW_TYPE_TASK_MARKUP_LABEL, TaskRowTaskMarkupLabelClass))
#define TASK_ROW_IS_TASK_MARKUP_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TASK_ROW_TYPE_TASK_MARKUP_LABEL))
#define TASK_ROW_IS_TASK_MARKUP_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TASK_ROW_TYPE_TASK_MARKUP_LABEL))
#define TASK_ROW_TASK_MARKUP_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TASK_ROW_TYPE_TASK_MARKUP_LABEL, TaskRowTaskMarkupLabelClass))

typedef struct _TaskRowTaskMarkupLabel TaskRowTaskMarkupLabel;
typedef struct _TaskRowTaskMarkupLabelClass TaskRowTaskMarkupLabelClass;

#define TASK_ROW_TYPE_TASK_EDIT_ENTRY (task_row_task_edit_entry_get_type ())
#define TASK_ROW_TASK_EDIT_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TASK_ROW_TYPE_TASK_EDIT_ENTRY, TaskRowTaskEditEntry))
#define TASK_ROW_TASK_EDIT_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TASK_ROW_TYPE_TASK_EDIT_ENTRY, TaskRowTaskEditEntryClass))
#define TASK_ROW_IS_TASK_EDIT_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TASK_ROW_TYPE_TASK_EDIT_ENTRY))
#define TASK_ROW_IS_TASK_EDIT_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TASK_ROW_TYPE_TASK_EDIT_ENTRY))
#define TASK_ROW_TASK_EDIT_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TASK_ROW_TYPE_TASK_EDIT_ENTRY, TaskRowTaskEditEntryClass))

typedef struct _TaskRowTaskEditEntry TaskRowTaskEditEntry;
typedef struct _TaskRowTaskEditEntryClass TaskRowTaskEditEntryClass;

#define TYPE_TODO_TASK (todo_task_get_type ())
#define TODO_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TODO_TASK, TodoTask))
#define TODO_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TODO_TASK, TodoTaskClass))
#define IS_TODO_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TODO_TASK))
#define IS_TODO_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TODO_TASK))
#define TODO_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TODO_TASK, TodoTaskClass))

typedef struct _TodoTask TodoTask;
typedef struct _TodoTaskClass TodoTaskClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _TaskRowTaskEditEntryPrivate TaskRowTaskEditEntryPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _TaskRowTaskMarkupLabelPrivate TaskRowTaskMarkupLabelPrivate;
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _DragListRow {
	GtkListBoxRow parent_instance;
	DragListRowPrivate * priv;
};

struct _DragListRowClass {
	GtkListBoxRowClass parent_class;
};

struct _TaskRow {
	DragListRow parent_instance;
	TaskRowPrivate * priv;
};

struct _TaskRowClass {
	DragListRowClass parent_class;
};

struct _TaskRowPrivate {
	GtkCheckButton* check_button;
	GtkButton* delete_button;
	TaskRowTaskMarkupLabel* markup_label;
	TaskRowTaskEditEntry* edit_entry;
	gboolean editing;
	gboolean focus_cooldown_active;
	TodoTask* _task;
};

struct _TaskRowTaskEditEntry {
	GtkEntry parent_instance;
	TaskRowTaskEditEntryPrivate * priv;
};

struct _TaskRowTaskEditEntryClass {
	GtkEntryClass parent_class;
};

struct _TaskRowTaskEditEntryPrivate {
	gchar* _description;
	gchar* _priority;
};

struct _TaskRowTaskMarkupLabel {
	GtkLabel parent_instance;
	TaskRowTaskMarkupLabelPrivate * priv;
};

struct _TaskRowTaskMarkupLabelClass {
	GtkLabelClass parent_class;
};

struct _TaskRowTaskMarkupLabelPrivate {
	TodoTask* task;
	gchar* markup_string;
};


static gpointer task_row_parent_class = NULL;
static gpointer task_row_task_edit_entry_parent_class = NULL;
static gpointer task_row_task_markup_label_parent_class = NULL;

GType drag_list_row_get_type (void) G_GNUC_CONST;
GType task_row_get_type (void) G_GNUC_CONST;
static GType task_row_task_markup_label_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static GType task_row_task_edit_entry_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
GType todo_task_get_type (void) G_GNUC_CONST;
#define TASK_ROW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TASK_ROW, TaskRowPrivate))
enum  {
	TASK_ROW_DUMMY_PROPERTY,
	TASK_ROW_TASK
};
TaskRow* task_row_new (TodoTask* task);
TaskRow* task_row_construct (GType object_type, TodoTask* task);
DragListRow* drag_list_row_new (void);
DragListRow* drag_list_row_construct (GType object_type);
static void task_row_set_task (TaskRow* self, TodoTask* value);
static TaskRowTaskMarkupLabel* task_row_task_markup_label_new (TodoTask* task);
static TaskRowTaskMarkupLabel* task_row_task_markup_label_construct (GType object_type, TodoTask* task);
gboolean todo_task_get_done (TodoTask* self);
void drag_list_row_set_start_widget (DragListRow* self, GtkWidget* widget);
void drag_list_row_set_center_widget (DragListRow* self, GtkWidget* widget);
static void task_row_connect_signals (TaskRow* self);
void task_row_edit (TaskRow* self);
static void __lambda13_ (TaskRow* self);
static void ___lambda13__gtk_button_clicked (GtkButton* _sender, gpointer self);
TodoTask* task_row_get_task (TaskRow* self);
const gchar* todo_task_get_description (TodoTask* self);
const gchar* todo_task_get_priority (TodoTask* self);
static TaskRowTaskEditEntry* task_row_task_edit_entry_new (const gchar* description, const gchar* priority);
static TaskRowTaskEditEntry* task_row_task_edit_entry_construct (GType object_type, const gchar* description, const gchar* priority);
static void task_row_task_edit_entry_edit (TaskRowTaskEditEntry* self);
static void __lambda14_ (TaskRow* self);
static const gchar* task_row_task_edit_entry_get_description (TaskRowTaskEditEntry* self);
void todo_task_set_description (TodoTask* self, const gchar* value);
static const gchar* task_row_task_edit_entry_get_priority (TaskRowTaskEditEntry* self);
void todo_task_set_priority (TodoTask* self, const gchar* value);
static void ___lambda14__task_row_task_edit_entry_strings_changed (TaskRowTaskEditEntry* _sender, gpointer self);
static void __lambda15_ (TaskRow* self);
void task_row_stop_editing (TaskRow* self);
static void ___lambda15__task_row_task_edit_entry_editing_finished (TaskRowTaskEditEntry* _sender, gpointer self);
static gboolean task_row_on_focus_out (TaskRow* self);
static gboolean task_row_focus_cooldown_end (TaskRow* self);
static gboolean _task_row_focus_cooldown_end_gsource_func (gpointer self);
static gboolean task_row_on_row_key_release (TaskRow* self, GdkEventKey* event);
static void __lambda9_ (TaskRow* self);
void todo_task_set_done (TodoTask* self, gboolean value);
static void ___lambda9__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void __lambda10_ (TaskRow* self);
static void ___lambda10__todo_task_done_changed (TodoTask* _sender, gpointer self);
static gboolean __lambda11_ (TaskRow* self, const gchar* uri);
static gboolean ___lambda11__gtk_label_activate_link (GtkLabel* _sender, const gchar* uri, gpointer self);
static void __lambda12_ (TaskRow* self, GtkWidget* widget);
static void ___lambda12__gtk_container_set_focus_child (GtkContainer* _sender, GtkWidget* child, gpointer self);
static gboolean _task_row_on_focus_out_gtk_widget_focus_out_event (GtkWidget* _sender, GdkEventFocus* event, gpointer self);
static gboolean _task_row_on_row_key_release_gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
#define TASK_ROW_TASK_EDIT_ENTRY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TASK_ROW_TYPE_TASK_EDIT_ENTRY, TaskRowTaskEditEntryPrivate))
enum  {
	TASK_ROW_TASK_EDIT_ENTRY_DUMMY_PROPERTY,
	TASK_ROW_TASK_EDIT_ENTRY_DESCRIPTION,
	TASK_ROW_TASK_EDIT_ENTRY_PRIORITY
};
static void task_row_task_edit_entry_set_description (TaskRowTaskEditEntry* self, const gchar* value);
static void task_row_task_edit_entry_set_priority (TaskRowTaskEditEntry* self, const gchar* value);
static void task_row_task_edit_entry_split_pseudo_description (TaskRowTaskEditEntry* self, const gchar* pseudo_description);
gchar* gofi_txt_utils_consume_priority (gchar** pseudo_description);
static void task_row_task_edit_entry_abort_editing (TaskRowTaskEditEntry* self);
static void task_row_task_edit_entry_stop_editing (TaskRowTaskEditEntry* self);
static void _task_row_task_edit_entry_stop_editing_gtk_entry_activate (GtkEntry* _sender, gpointer self);
static void task_row_task_edit_entry_finalize (GObject* obj);
static void _vala_task_row_task_edit_entry_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_task_row_task_edit_entry_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
#define TASK_ROW_TASK_MARKUP_LABEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TASK_ROW_TYPE_TASK_MARKUP_LABEL, TaskRowTaskMarkupLabelPrivate))
enum  {
	TASK_ROW_TASK_MARKUP_LABEL_DUMMY_PROPERTY
};
static void task_row_task_markup_label_update (TaskRowTaskMarkupLabel* self);
static void task_row_task_markup_label_update_tooltip (TaskRowTaskMarkupLabel* self);
static void task_row_task_markup_label_connect_signals (TaskRowTaskMarkupLabel* self);
GDateTime* todo_task_get_completion_date (TodoTask* self);
GDateTime* todo_task_get_creation_date (TodoTask* self);
static void task_row_task_markup_label_gen_markup (TaskRowTaskMarkupLabel* self);
static gchar* task_row_task_markup_label_make_links (TaskRowTaskMarkupLabel* self, const gchar* description);
gboolean gofi_txt_utils_is_context_tag (const gchar* token);
gboolean gofi_txt_utils_is_project_tag (const gchar* token);
static void _task_row_task_markup_label_update_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void task_row_task_markup_label_finalize (GObject* obj);
static void task_row_finalize (GObject* obj);
static void _vala_task_row_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_task_row_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


TaskRow* task_row_construct (GType object_type, TodoTask* task) {
	TaskRow * self = NULL;
	TodoTask* _tmp0_ = NULL;
	TodoTask* _tmp1_ = NULL;
	TaskRowTaskMarkupLabel* _tmp2_ = NULL;
	GtkCheckButton* _tmp3_ = NULL;
	GtkCheckButton* _tmp4_ = NULL;
	TodoTask* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	gboolean _tmp7_ = FALSE;
	GtkCheckButton* _tmp8_ = NULL;
	TaskRowTaskMarkupLabel* _tmp9_ = NULL;
#line 36 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (task != NULL, NULL);
#line 36 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self = (TaskRow*) drag_list_row_construct (object_type);
#line 37 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = task;
#line 37 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_set_task (self, _tmp0_);
#line 39 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->edit_entry);
#line 39 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->edit_entry = NULL;
#line 40 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->editing = FALSE;
#line 41 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->focus_cooldown_active = FALSE;
#line 42 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = task;
#line 42 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = task_row_task_markup_label_new (_tmp1_);
#line 42 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_ref_sink (_tmp2_);
#line 42 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->markup_label);
#line 42 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->markup_label = _tmp2_;
#line 44 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp3_ = (GtkCheckButton*) gtk_check_button_new ();
#line 44 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_ref_sink (_tmp3_);
#line 44 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->check_button);
#line 44 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->check_button = _tmp3_;
#line 45 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp4_ = self->priv->check_button;
#line 45 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp5_ = task;
#line 45 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp6_ = todo_task_get_done (_tmp5_);
#line 45 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp7_ = _tmp6_;
#line 45 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp4_, _tmp7_);
#line 47 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp8_ = self->priv->check_button;
#line 47 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	drag_list_row_set_start_widget ((DragListRow*) self, (GtkWidget*) _tmp8_);
#line 48 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp9_ = self->priv->markup_label;
#line 48 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	drag_list_row_set_center_widget ((DragListRow*) self, (GtkWidget*) _tmp9_);
#line 50 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_connect_signals (self);
#line 51 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 36 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return self;
#line 313 "TaskRow.c"
}


TaskRow* task_row_new (TodoTask* task) {
#line 36 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return task_row_construct (TYPE_TASK_ROW, task);
#line 320 "TaskRow.c"
}


static void __lambda13_ (TaskRow* self) {
#line 62 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_emit_by_name (self, "deletion-requested");
#line 327 "TaskRow.c"
}


static void ___lambda13__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 61 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	__lambda13_ ((TaskRow*) self);
#line 334 "TaskRow.c"
}


static void __lambda14_ (TaskRow* self) {
	TodoTask* _tmp0_ = NULL;
	TaskRowTaskEditEntry* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	TodoTask* _tmp4_ = NULL;
	TaskRowTaskEditEntry* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
#line 71 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->_task;
#line 71 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = self->priv->edit_entry;
#line 71 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = task_row_task_edit_entry_get_description (_tmp1_);
#line 71 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp3_ = _tmp2_;
#line 71 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	todo_task_set_description (_tmp0_, _tmp3_);
#line 72 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp4_ = self->priv->_task;
#line 72 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp5_ = self->priv->edit_entry;
#line 72 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp6_ = task_row_task_edit_entry_get_priority (_tmp5_);
#line 72 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp7_ = _tmp6_;
#line 72 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	todo_task_set_priority (_tmp4_, _tmp7_);
#line 367 "TaskRow.c"
}


static void ___lambda14__task_row_task_edit_entry_strings_changed (TaskRowTaskEditEntry* _sender, gpointer self) {
#line 70 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	__lambda14_ ((TaskRow*) self);
#line 374 "TaskRow.c"
}


static void __lambda15_ (TaskRow* self) {
#line 75 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_stop_editing (self);
#line 381 "TaskRow.c"
}


static void ___lambda15__task_row_task_edit_entry_editing_finished (TaskRowTaskEditEntry* _sender, gpointer self) {
#line 74 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	__lambda15_ ((TaskRow*) self);
#line 388 "TaskRow.c"
}


void task_row_edit (TaskRow* self) {
	TaskRowTaskEditEntry* _tmp0_ = NULL;
	GtkButton* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	GtkButton* _tmp3_ = NULL;
	GtkButton* _tmp4_ = NULL;
	GtkButton* _tmp5_ = NULL;
	TodoTask* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	TodoTask* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	TaskRowTaskEditEntry* _tmp12_ = NULL;
	TaskRowTaskEditEntry* _tmp13_ = NULL;
	TaskRowTaskEditEntry* _tmp14_ = NULL;
	TaskRowTaskEditEntry* _tmp15_ = NULL;
	TaskRowTaskEditEntry* _tmp16_ = NULL;
#line 54 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 55 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->edit_entry;
#line 55 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp0_ != NULL) {
#line 56 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		return;
#line 418 "TaskRow.c"
	}
#line 58 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = (GtkButton*) gtk_button_new_from_icon_name ("edit-delete", GTK_ICON_SIZE_MENU);
#line 58 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_ref_sink (_tmp1_);
#line 58 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->delete_button);
#line 58 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->delete_button = _tmp1_;
#line 59 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = self->priv->delete_button;
#line 59 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	gtk_button_set_relief (_tmp2_, GTK_RELIEF_NONE);
#line 60 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp3_ = self->priv->delete_button;
#line 60 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp3_);
#line 61 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp4_ = self->priv->delete_button;
#line 61 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object (_tmp4_, "clicked", (GCallback) ___lambda13__gtk_button_clicked, self, 0);
#line 64 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp5_ = self->priv->delete_button;
#line 64 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	drag_list_row_set_start_widget ((DragListRow*) self, (GtkWidget*) _tmp5_);
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp6_ = self->priv->_task;
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp7_ = todo_task_get_description (_tmp6_);
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp8_ = _tmp7_;
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp9_ = self->priv->_task;
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp10_ = todo_task_get_priority (_tmp9_);
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp11_ = _tmp10_;
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp12_ = task_row_task_edit_entry_new (_tmp8_, _tmp11_);
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_ref_sink (_tmp12_);
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->edit_entry);
#line 66 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->edit_entry = _tmp12_;
#line 67 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp13_ = self->priv->edit_entry;
#line 67 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	drag_list_row_set_center_widget ((DragListRow*) self, (GtkWidget*) _tmp13_);
#line 69 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp14_ = self->priv->edit_entry;
#line 69 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_edit_entry_edit (_tmp14_);
#line 70 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp15_ = self->priv->edit_entry;
#line 70 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object (_tmp15_, "strings-changed", (GCallback) ___lambda14__task_row_task_edit_entry_strings_changed, self, 0);
#line 74 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp16_ = self->priv->edit_entry;
#line 74 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object (_tmp16_, "editing-finished", (GCallback) ___lambda15__task_row_task_edit_entry_editing_finished, self, 0);
#line 77 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->editing = TRUE;
#line 482 "TaskRow.c"
}


/**
     * Using a cooldown to work around a Gtk issue:
     * The ListBoxRow will steal focus again after activating and in addition
     * to that for a moment neither the row nor the entry may have focus.
     * We give everything a moment to settle and stop editing as soon as neither
     * this row or the entry has focus.
     */
static gboolean _task_row_focus_cooldown_end_gsource_func (gpointer self) {
	gboolean result;
	result = task_row_focus_cooldown_end ((TaskRow*) self);
#line 92 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 498 "TaskRow.c"
}


static gboolean task_row_on_focus_out (TaskRow* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
#line 87 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 88 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->focus_cooldown_active;
#line 88 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = self->priv->editing;
#line 88 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp0_ | (!_tmp1_)) {
#line 89 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		result = FALSE;
#line 89 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		return result;
#line 518 "TaskRow.c"
	}
#line 91 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->focus_cooldown_active = TRUE;
#line 92 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_timeout_add_full (G_PRIORITY_DEFAULT_IDLE, (guint) 50, _task_row_focus_cooldown_end_gsource_func, g_object_ref (self), g_object_unref);
#line 95 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	result = FALSE;
#line 95 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 528 "TaskRow.c"
}


static gboolean task_row_focus_cooldown_end (TaskRow* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
#line 98 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 99 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->focus_cooldown_active = FALSE;
#line 100 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->editing;
#line 100 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (!_tmp0_) {
#line 101 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		result = FALSE;
#line 101 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		return result;
#line 550 "TaskRow.c"
	}
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_get ((GtkWidget*) self, "has-focus", &_tmp2_, NULL);
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp3_ = _tmp2_;
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (!_tmp3_) {
#line 558 "TaskRow.c"
		GtkWidget* _tmp4_ = NULL;
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp4_ = gtk_container_get_focus_child ((GtkContainer*) self);
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp1_ = _tmp4_ == NULL;
#line 564 "TaskRow.c"
	} else {
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp1_ = FALSE;
#line 568 "TaskRow.c"
	}
#line 103 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp1_) {
#line 104 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		task_row_stop_editing (self);
#line 105 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		result = FALSE;
#line 105 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		return result;
#line 578 "TaskRow.c"
	}
#line 107 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	result = G_SOURCE_REMOVE;
#line 107 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 584 "TaskRow.c"
}


void task_row_stop_editing (TaskRow* self) {
	gboolean _tmp0_ = FALSE;
	TaskRowTaskMarkupLabel* _tmp1_ = NULL;
	GtkCheckButton* _tmp2_ = NULL;
#line 110 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 111 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->editing;
#line 111 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (!_tmp0_) {
#line 112 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		return;
#line 600 "TaskRow.c"
	}
#line 114 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = self->priv->markup_label;
#line 114 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	drag_list_row_set_center_widget ((DragListRow*) self, (GtkWidget*) _tmp1_);
#line 115 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = self->priv->check_button;
#line 115 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	drag_list_row_set_start_widget ((DragListRow*) self, (GtkWidget*) _tmp2_);
#line 116 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->delete_button);
#line 116 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->delete_button = NULL;
#line 117 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->edit_entry);
#line 117 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->edit_entry = NULL;
#line 118 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->editing = FALSE;
#line 620 "TaskRow.c"
}


static gboolean task_row_on_row_key_release (TaskRow* self, GdkEventKey* event) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	GdkEventKey* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
#line 121 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 121 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = event;
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = _tmp1_->keyval;
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp2_ == ((guint) GDK_KEY_Delete)) {
#line 639 "TaskRow.c"
		gboolean _tmp3_ = FALSE;
		gboolean _tmp4_ = FALSE;
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp4_ = self->priv->editing;
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		if (!_tmp4_) {
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp3_ = TRUE;
#line 648 "TaskRow.c"
		} else {
			TaskRowTaskEditEntry* _tmp5_ = NULL;
			gboolean _tmp6_ = FALSE;
			gboolean _tmp7_ = FALSE;
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp5_ = self->priv->edit_entry;
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			g_object_get ((GtkWidget*) _tmp5_, "has-focus", &_tmp6_, NULL);
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp7_ = _tmp6_;
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp3_ = !_tmp7_;
#line 661 "TaskRow.c"
		}
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp0_ = _tmp3_;
#line 665 "TaskRow.c"
	} else {
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp0_ = FALSE;
#line 669 "TaskRow.c"
	}
#line 122 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp0_) {
#line 123 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		g_signal_emit_by_name (self, "deletion-requested");
#line 124 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		result = TRUE;
#line 124 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		return result;
#line 679 "TaskRow.c"
	}
#line 126 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	result = FALSE;
#line 126 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 685 "TaskRow.c"
}


static void __lambda9_ (TaskRow* self) {
	TodoTask* _tmp0_ = NULL;
	TodoTask* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
#line 131 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->_task;
#line 131 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = self->priv->_task;
#line 131 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = todo_task_get_done (_tmp1_);
#line 131 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp3_ = _tmp2_;
#line 131 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	todo_task_set_done (_tmp0_, !_tmp3_);
#line 704 "TaskRow.c"
}


static void ___lambda9__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
#line 130 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	__lambda9_ ((TaskRow*) self);
#line 711 "TaskRow.c"
}


static void __lambda10_ (TaskRow* self) {
#line 134 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 718 "TaskRow.c"
}


static void ___lambda10__todo_task_done_changed (TodoTask* _sender, gpointer self) {
#line 133 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	__lambda10_ ((TaskRow*) self);
#line 725 "TaskRow.c"
}


static gboolean __lambda11_ (TaskRow* self, const gchar* uri) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
#line 136 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (uri != NULL, FALSE);
#line 137 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = uri;
#line 137 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_emit_by_name (self, "link-clicked", _tmp0_);
#line 138 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	result = TRUE;
#line 138 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 742 "TaskRow.c"
}


static gboolean ___lambda11__gtk_label_activate_link (GtkLabel* _sender, const gchar* uri, gpointer self) {
	gboolean result;
	result = __lambda11_ ((TaskRow*) self, uri);
#line 136 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 751 "TaskRow.c"
}


static void __lambda12_ (TaskRow* self, GtkWidget* widget) {
	gboolean _tmp0_ = FALSE;
	GtkWidget* _tmp1_ = NULL;
#line 141 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = widget;
#line 141 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp1_ == NULL) {
#line 762 "TaskRow.c"
		gboolean _tmp2_ = FALSE;
		gboolean _tmp3_ = FALSE;
#line 141 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		g_object_get ((GtkWidget*) self, "has-focus", &_tmp2_, NULL);
#line 141 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp3_ = _tmp2_;
#line 141 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp0_ = !_tmp3_;
#line 771 "TaskRow.c"
	} else {
#line 141 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp0_ = FALSE;
#line 775 "TaskRow.c"
	}
#line 141 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp0_) {
#line 142 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		task_row_on_focus_out (self);
#line 781 "TaskRow.c"
	}
}


static void ___lambda12__gtk_container_set_focus_child (GtkContainer* _sender, GtkWidget* child, gpointer self) {
#line 140 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	__lambda12_ ((TaskRow*) self, child);
#line 789 "TaskRow.c"
}


static gboolean _task_row_on_focus_out_gtk_widget_focus_out_event (GtkWidget* _sender, GdkEventFocus* event, gpointer self) {
	gboolean result;
	result = task_row_on_focus_out ((TaskRow*) self);
#line 145 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 798 "TaskRow.c"
}


static gboolean _task_row_on_row_key_release_gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	gboolean result;
	result = task_row_on_row_key_release ((TaskRow*) self, event);
#line 146 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 807 "TaskRow.c"
}


static void task_row_connect_signals (TaskRow* self) {
	GtkCheckButton* _tmp0_ = NULL;
	TodoTask* _tmp1_ = NULL;
	TaskRowTaskMarkupLabel* _tmp2_ = NULL;
#line 129 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 130 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->check_button;
#line 130 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object ((GtkToggleButton*) _tmp0_, "toggled", (GCallback) ___lambda9__gtk_toggle_button_toggled, self, 0);
#line 133 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = self->priv->_task;
#line 133 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object (_tmp1_, "done-changed", (GCallback) ___lambda10__todo_task_done_changed, self, 0);
#line 136 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = self->priv->markup_label;
#line 136 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object ((GtkLabel*) _tmp2_, "activate-link", (GCallback) ___lambda11__gtk_label_activate_link, self, 0);
#line 140 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object ((GtkContainer*) self, "set-focus-child", (GCallback) ___lambda12__gtk_container_set_focus_child, self, 0);
#line 145 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object ((GtkWidget*) self, "focus-out-event", (GCallback) _task_row_on_focus_out_gtk_widget_focus_out_event, self, 0);
#line 146 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object ((GtkWidget*) self, "key-release-event", (GCallback) _task_row_on_row_key_release_gtk_widget_key_release_event, self, 0);
#line 835 "TaskRow.c"
}


TodoTask* task_row_get_task (TaskRow* self) {
	TodoTask* result;
	TodoTask* _tmp0_ = NULL;
#line 29 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 29 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->_task;
#line 29 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	result = _tmp0_;
#line 29 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 850 "TaskRow.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 30 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return self ? g_object_ref (self) : NULL;
#line 857 "TaskRow.c"
}


static void task_row_set_task (TaskRow* self, TodoTask* value) {
	TodoTask* _tmp0_ = NULL;
	TodoTask* _tmp1_ = NULL;
#line 30 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 30 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = value;
#line 30 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 30 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->_task);
#line 30 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->_task = _tmp1_;
#line 30 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_notify ((GObject *) self, "task");
#line 876 "TaskRow.c"
}


static TaskRowTaskEditEntry* task_row_task_edit_entry_construct (GType object_type, const gchar* description, const gchar* priority) {
	TaskRowTaskEditEntry * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
#line 173 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (description != NULL, NULL);
#line 173 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self = (TaskRowTaskEditEntry*) g_object_new (object_type, NULL);
#line 174 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = description;
#line 174 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_edit_entry_set_description (self, _tmp0_);
#line 175 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = priority;
#line 175 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_edit_entry_set_priority (self, _tmp1_);
#line 177 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_set ((GtkWidget*) self, "can-focus", TRUE, NULL);
#line 178 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = priority;
#line 178 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp2_ == NULL) {
#line 903 "TaskRow.c"
		const gchar* _tmp3_ = NULL;
#line 179 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp3_ = self->priv->_description;
#line 179 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		gtk_entry_set_text ((GtkEntry*) self, _tmp3_);
#line 909 "TaskRow.c"
	} else {
		const gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
#line 181 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp4_ = self->priv->_priority;
#line 181 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp5_ = g_strconcat (_tmp4_, " ", NULL);
#line 181 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp6_ = _tmp5_;
#line 181 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp7_ = self->priv->_description;
#line 181 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp8_ = g_strconcat (_tmp6_, _tmp7_, NULL);
#line 181 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp9_ = _tmp8_;
#line 181 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		gtk_entry_set_text ((GtkEntry*) self, _tmp9_);
#line 181 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_g_free0 (_tmp9_);
#line 181 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_g_free0 (_tmp6_);
#line 935 "TaskRow.c"
	}
#line 173 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return self;
#line 939 "TaskRow.c"
}


static TaskRowTaskEditEntry* task_row_task_edit_entry_new (const gchar* description, const gchar* priority) {
#line 173 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return task_row_task_edit_entry_construct (TASK_ROW_TYPE_TASK_EDIT_ENTRY, description, priority);
#line 946 "TaskRow.c"
}


static void task_row_task_edit_entry_split_pseudo_description (TaskRowTaskEditEntry* self, const gchar* pseudo_description) {
	gchar* _pseudo_description = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
#line 185 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 185 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (pseudo_description != NULL);
#line 186 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = pseudo_description;
#line 186 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 186 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_pseudo_description = _tmp1_;
#line 187 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = gofi_txt_utils_consume_priority (&_pseudo_description);
#line 187 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (self->priv->_priority);
#line 187 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->_priority = _tmp2_;
#line 188 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp3_ = _pseudo_description;
#line 188 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_edit_entry_set_description (self, _tmp3_);
#line 185 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (_pseudo_description);
#line 978 "TaskRow.c"
}


static void task_row_task_edit_entry_abort_editing (TaskRowTaskEditEntry* self) {
#line 191 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 192 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_emit_by_name (self, "editing-finished");
#line 987 "TaskRow.c"
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 1207 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1208 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1208 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1209 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1209 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_strstrip (_tmp1_);
#line 1210 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	result = _result_;
#line 1210 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	return result;
#line 1010 "TaskRow.c"
}


static void task_row_task_edit_entry_stop_editing (TaskRowTaskEditEntry* self) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 195 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 196 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = gtk_entry_get_text ((GtkEntry*) self);
#line 196 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = _tmp0_;
#line 196 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = string_strip (_tmp1_);
#line 196 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp3_ = _tmp2_;
#line 196 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_edit_entry_split_pseudo_description (self, _tmp3_);
#line 196 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (_tmp3_);
#line 197 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_emit_by_name (self, "strings-changed");
#line 198 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_edit_entry_abort_editing (self);
#line 1037 "TaskRow.c"
}


static void _task_row_task_edit_entry_stop_editing_gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 204 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_edit_entry_stop_editing ((TaskRowTaskEditEntry*) self);
#line 1044 "TaskRow.c"
}


static void task_row_task_edit_entry_edit (TaskRowTaskEditEntry* self) {
#line 201 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 202 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	gtk_widget_show ((GtkWidget*) self);
#line 203 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	gtk_widget_grab_focus ((GtkWidget*) self);
#line 204 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object ((GtkEntry*) self, "activate", (GCallback) _task_row_task_edit_entry_stop_editing_gtk_entry_activate, self, 0);
#line 1057 "TaskRow.c"
}


static const gchar* task_row_task_edit_entry_get_description (TaskRowTaskEditEntry* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 152 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 153 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->_description;
#line 153 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	result = _tmp0_;
#line 153 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 1072 "TaskRow.c"
}


static void task_row_task_edit_entry_set_description (TaskRowTaskEditEntry* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 155 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 156 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = value;
#line 156 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 156 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (self->priv->_description);
#line 156 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->_description = _tmp1_;
#line 155 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_notify ((GObject *) self, "description");
#line 1091 "TaskRow.c"
}


static const gchar* task_row_task_edit_entry_get_priority (TaskRowTaskEditEntry* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 162 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 163 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->_priority;
#line 163 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	result = _tmp0_;
#line 163 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 1106 "TaskRow.c"
}


static void task_row_task_edit_entry_set_priority (TaskRowTaskEditEntry* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 165 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 166 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = value;
#line 166 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 166 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (self->priv->_priority);
#line 166 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->_priority = _tmp1_;
#line 165 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_notify ((GObject *) self, "priority");
#line 1125 "TaskRow.c"
}


static void task_row_task_edit_entry_class_init (TaskRowTaskEditEntryClass * klass) {
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_edit_entry_parent_class = g_type_class_peek_parent (klass);
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_type_class_add_private (klass, sizeof (TaskRowTaskEditEntryPrivate));
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_task_row_task_edit_entry_get_property;
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_task_row_task_edit_entry_set_property;
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	G_OBJECT_CLASS (klass)->finalize = task_row_task_edit_entry_finalize;
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TASK_ROW_TASK_EDIT_ENTRY_DESCRIPTION, g_param_spec_string ("description", "description", "description", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TASK_ROW_TASK_EDIT_ENTRY_PRIORITY, g_param_spec_string ("priority", "priority", "priority", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_new ("editing_finished", TASK_ROW_TYPE_TASK_EDIT_ENTRY, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_new ("strings_changed", TASK_ROW_TYPE_TASK_EDIT_ENTRY, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 1148 "TaskRow.c"
}


static void task_row_task_edit_entry_instance_init (TaskRowTaskEditEntry * self) {
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv = TASK_ROW_TASK_EDIT_ENTRY_GET_PRIVATE (self);
#line 1155 "TaskRow.c"
}


static void task_row_task_edit_entry_finalize (GObject* obj) {
	TaskRowTaskEditEntry * self;
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TASK_ROW_TYPE_TASK_EDIT_ENTRY, TaskRowTaskEditEntry);
#line 150 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (self->priv->_description);
#line 160 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (self->priv->_priority);
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	G_OBJECT_CLASS (task_row_task_edit_entry_parent_class)->finalize (obj);
#line 1169 "TaskRow.c"
}


static GType task_row_task_edit_entry_get_type (void) {
	static volatile gsize task_row_task_edit_entry_type_id__volatile = 0;
	if (g_once_init_enter (&task_row_task_edit_entry_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TaskRowTaskEditEntryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) task_row_task_edit_entry_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TaskRowTaskEditEntry), 0, (GInstanceInitFunc) task_row_task_edit_entry_instance_init, NULL };
		GType task_row_task_edit_entry_type_id;
		task_row_task_edit_entry_type_id = g_type_register_static (gtk_entry_get_type (), "TaskRowTaskEditEntry", &g_define_type_info, 0);
		g_once_init_leave (&task_row_task_edit_entry_type_id__volatile, task_row_task_edit_entry_type_id);
	}
	return task_row_task_edit_entry_type_id__volatile;
}


static void _vala_task_row_task_edit_entry_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TaskRowTaskEditEntry * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TASK_ROW_TYPE_TASK_EDIT_ENTRY, TaskRowTaskEditEntry);
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	switch (property_id) {
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		case TASK_ROW_TASK_EDIT_ENTRY_DESCRIPTION:
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		g_value_set_string (value, task_row_task_edit_entry_get_description (self));
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		break;
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		case TASK_ROW_TASK_EDIT_ENTRY_PRIORITY:
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		g_value_set_string (value, task_row_task_edit_entry_get_priority (self));
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		break;
#line 1202 "TaskRow.c"
		default:
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		break;
#line 1208 "TaskRow.c"
	}
}


static void _vala_task_row_task_edit_entry_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TaskRowTaskEditEntry * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TASK_ROW_TYPE_TASK_EDIT_ENTRY, TaskRowTaskEditEntry);
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	switch (property_id) {
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		case TASK_ROW_TASK_EDIT_ENTRY_DESCRIPTION:
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		task_row_task_edit_entry_set_description (self, g_value_get_string (value));
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		break;
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		case TASK_ROW_TASK_EDIT_ENTRY_PRIORITY:
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		task_row_task_edit_entry_set_priority (self, g_value_get_string (value));
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		break;
#line 1230 "TaskRow.c"
		default:
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 149 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		break;
#line 1236 "TaskRow.c"
	}
}


static TaskRowTaskMarkupLabel* task_row_task_markup_label_construct (GType object_type, TodoTask* task) {
	TaskRowTaskMarkupLabel * self = NULL;
	TodoTask* _tmp0_ = NULL;
	TodoTask* _tmp1_ = NULL;
#line 213 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (task != NULL, NULL);
#line 213 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self = (TaskRowTaskMarkupLabel*) g_object_new (object_type, NULL);
#line 214 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = task;
#line 214 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 214 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->task);
#line 214 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->task = _tmp1_;
#line 216 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_markup_label_update (self);
#line 218 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	gtk_widget_set_hexpand ((GtkWidget*) self, TRUE);
#line 219 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_set ((GtkLabel*) self, "wrap", TRUE, NULL);
#line 220 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_set ((GtkLabel*) self, "wrap-mode", PANGO_WRAP_WORD_CHAR, NULL);
#line 221 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_set ((GtkWidget*) self, "width-request", 200, NULL);
#line 223 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_set (G_TYPE_CHECK_INSTANCE_CAST (self, gtk_misc_get_type (), GtkMisc), "xalign", 0.f, NULL);
#line 225 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_markup_label_update_tooltip (self);
#line 227 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_markup_label_connect_signals (self);
#line 228 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 213 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return self;
#line 1277 "TaskRow.c"
}


static TaskRowTaskMarkupLabel* task_row_task_markup_label_new (TodoTask* task) {
#line 213 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return task_row_task_markup_label_construct (TASK_ROW_TYPE_TASK_MARKUP_LABEL, task);
#line 1284 "TaskRow.c"
}


static gpointer _g_date_time_ref0 (gpointer self) {
#line 232 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return self ? g_date_time_ref (self) : NULL;
#line 1291 "TaskRow.c"
}


static void task_row_task_markup_label_update_tooltip (TaskRowTaskMarkupLabel* self) {
	GDateTime* completion_date = NULL;
	TodoTask* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	GDateTime* _tmp2_ = NULL;
	GDateTime* _tmp3_ = NULL;
	GDateTime* creation_date = NULL;
	TodoTask* _tmp4_ = NULL;
	GDateTime* _tmp5_ = NULL;
	GDateTime* _tmp6_ = NULL;
	GDateTime* _tmp7_ = NULL;
	gchar* date_format = NULL;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gboolean _tmp10_ = FALSE;
	TodoTask* _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	gboolean _tmp13_ = FALSE;
#line 231 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 232 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->task;
#line 232 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = todo_task_get_completion_date (_tmp0_);
#line 232 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = _tmp1_;
#line 232 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp3_ = _g_date_time_ref0 (_tmp2_);
#line 232 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	completion_date = _tmp3_;
#line 233 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp4_ = self->priv->task;
#line 233 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp5_ = todo_task_get_creation_date (_tmp4_);
#line 233 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp6_ = _tmp5_;
#line 233 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp7_ = _g_date_time_ref0 (_tmp6_);
#line 233 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	creation_date = _tmp7_;
#line 237 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp8_ = _ ("%Y-%m-%d");
#line 237 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp9_ = g_strdup (_tmp8_);
#line 237 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	date_format = _tmp9_;
#line 239 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp11_ = self->priv->task;
#line 239 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp12_ = todo_task_get_done (_tmp11_);
#line 239 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp13_ = _tmp12_;
#line 239 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp13_) {
#line 1349 "TaskRow.c"
		GDateTime* _tmp14_ = NULL;
#line 239 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp14_ = completion_date;
#line 239 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp10_ = _tmp14_ != NULL;
#line 1355 "TaskRow.c"
	} else {
#line 239 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp10_ = FALSE;
#line 1359 "TaskRow.c"
	}
#line 239 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp10_) {
#line 1363 "TaskRow.c"
		const gchar* _tmp15_ = NULL;
		GDateTime* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		GDateTime* _tmp20_ = NULL;
		const gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_ = NULL;
		gchar* _tmp25_ = NULL;
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp15_ = _ ("Task completed at %s, created at %s");
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp16_ = completion_date;
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp17_ = date_format;
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp18_ = g_date_time_format (_tmp16_, _tmp17_);
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp19_ = _tmp18_;
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp20_ = creation_date;
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp21_ = date_format;
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp22_ = g_date_time_format (_tmp20_, _tmp21_);
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp23_ = _tmp22_;
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp24_ = g_strdup_printf (_tmp15_, _tmp19_, _tmp23_);
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp25_ = _tmp24_;
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		gtk_widget_set_tooltip_text ((GtkWidget*) self, _tmp25_);
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_g_free0 (_tmp25_);
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_g_free0 (_tmp23_);
#line 240 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_g_free0 (_tmp19_);
#line 1405 "TaskRow.c"
	} else {
		GDateTime* _tmp26_ = NULL;
#line 246 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp26_ = creation_date;
#line 246 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		if (_tmp26_ != NULL) {
#line 1412 "TaskRow.c"
			const gchar* _tmp27_ = NULL;
			GDateTime* _tmp28_ = NULL;
			const gchar* _tmp29_ = NULL;
			gchar* _tmp30_ = NULL;
			gchar* _tmp31_ = NULL;
			gchar* _tmp32_ = NULL;
			gchar* _tmp33_ = NULL;
#line 247 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp27_ = _ ("Task created at %s");
#line 247 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp28_ = creation_date;
#line 247 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp29_ = date_format;
#line 247 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp30_ = g_date_time_format (_tmp28_, _tmp29_);
#line 247 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp31_ = _tmp30_;
#line 247 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp32_ = g_strdup_printf (_tmp27_, _tmp31_);
#line 247 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp33_ = _tmp32_;
#line 247 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			gtk_widget_set_tooltip_text ((GtkWidget*) self, _tmp33_);
#line 247 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_g_free0 (_tmp33_);
#line 247 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_g_free0 (_tmp31_);
#line 1440 "TaskRow.c"
		}
	}
#line 231 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (date_format);
#line 231 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_date_time_unref0 (creation_date);
#line 231 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_date_time_unref0 (completion_date);
#line 1449 "TaskRow.c"
}


static void task_row_task_markup_label_gen_markup (TaskRowTaskMarkupLabel* self) {
	TodoTask* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	TodoTask* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	TodoTask* _tmp18_ = NULL;
	gboolean _tmp19_ = FALSE;
	gboolean _tmp20_ = FALSE;
#line 255 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 256 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->task;
#line 256 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = todo_task_get_description (_tmp0_);
#line 256 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp2_ = _tmp1_;
#line 256 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp3_ = g_markup_escape_text (_tmp2_, (gssize) -1);
#line 256 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp4_ = _tmp3_;
#line 256 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp5_ = task_row_task_markup_label_make_links (self, _tmp4_);
#line 256 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (self->priv->markup_string);
#line 256 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv->markup_string = _tmp5_;
#line 256 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (_tmp4_);
#line 257 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp6_ = self->priv->task;
#line 257 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp7_ = todo_task_get_priority (_tmp6_);
#line 257 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp8_ = _tmp7_;
#line 257 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp8_ != NULL) {
#line 1494 "TaskRow.c"
		TodoTask* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		const gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		const gchar* _tmp16_ = NULL;
		gchar* _tmp17_ = NULL;
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp9_ = self->priv->task;
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp10_ = todo_task_get_priority (_tmp9_);
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp11_ = _tmp10_;
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp12_ = g_strconcat ("<b>", _tmp11_, NULL);
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp13_ = _tmp12_;
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp14_ = g_strconcat (_tmp13_, "</b> ", NULL);
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp15_ = _tmp14_;
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp16_ = self->priv->markup_string;
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp17_ = g_strconcat (_tmp15_, _tmp16_, NULL);
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_g_free0 (self->priv->markup_string);
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		self->priv->markup_string = _tmp17_;
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_g_free0 (_tmp15_);
#line 258 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_g_free0 (_tmp13_);
#line 1530 "TaskRow.c"
	}
#line 260 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp18_ = self->priv->task;
#line 260 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp19_ = todo_task_get_done (_tmp18_);
#line 260 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp20_ = _tmp19_;
#line 260 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	if (_tmp20_) {
#line 1540 "TaskRow.c"
		const gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_ = NULL;
#line 261 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp21_ = self->priv->markup_string;
#line 261 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp22_ = g_strconcat ("<s>", _tmp21_, NULL);
#line 261 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp23_ = _tmp22_;
#line 261 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_tmp24_ = g_strconcat (_tmp23_, "</s>", NULL);
#line 261 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_g_free0 (self->priv->markup_string);
#line 261 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		self->priv->markup_string = _tmp24_;
#line 261 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		_g_free0 (_tmp23_);
#line 1559 "TaskRow.c"
	}
}


/**
         * Used to find projects and contexts and replace those parts with a
         * link.
         * @param description the string to took for contexts or projects
         */
static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
#line 1412 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1413 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	result = self;
#line 1413 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	return result;
#line 1577 "TaskRow.c"
}


static gchar* string_chug (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 1199 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1200 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1200 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1201 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1201 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_strchug (_tmp1_);
#line 1202 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	result = _result_;
#line 1202 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	return result;
#line 1600 "TaskRow.c"
}


static gchar* task_row_task_markup_label_make_links (TaskRowTaskMarkupLabel* self, const gchar* description) {
	gchar* result = NULL;
	gchar* parsed = NULL;
	gchar* _tmp0_ = NULL;
	gchar* delimiter = NULL;
	gchar* prefix = NULL;
	const gchar* _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	const gchar* _tmp56_ = NULL;
	gchar* _tmp57_ = NULL;
#line 270 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 270 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_val_if_fail (description != NULL, NULL);
#line 271 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = g_strdup ("");
#line 271 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	parsed = _tmp0_;
#line 272 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	delimiter = NULL;
#line 272 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	prefix = NULL;
#line 274 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = description;
#line 274 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp3_ = _tmp2_ = g_strsplit (_tmp1_, " ", 0);
#line 1631 "TaskRow.c"
	{
		gchar** part_collection = NULL;
		gint part_collection_length1 = 0;
		gint _part_collection_size_ = 0;
		gint part_it = 0;
#line 274 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		part_collection = _tmp3_;
#line 274 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		part_collection_length1 = _vala_array_length (_tmp2_);
#line 274 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		for (part_it = 0; part_it < _vala_array_length (_tmp2_); part_it = part_it + 1) {
#line 1643 "TaskRow.c"
			gchar* _tmp4_ = NULL;
			gchar* part = NULL;
#line 274 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			_tmp4_ = g_strdup (part_collection[part_it]);
#line 274 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
			part = _tmp4_;
#line 1650 "TaskRow.c"
			{
				gchar* val = NULL;
				const gchar* _tmp5_ = NULL;
				const gchar* _tmp8_ = NULL;
				gboolean _tmp9_ = FALSE;
				const gchar* _tmp20_ = NULL;
				gboolean _tmp21_ = FALSE;
				const gchar* _tmp32_ = NULL;
#line 275 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				val = NULL;
#line 276 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				_tmp5_ = part;
#line 276 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				if (g_strcmp0 (_tmp5_, "") == 0) {
#line 1665 "TaskRow.c"
					const gchar* _tmp6_ = NULL;
					gchar* _tmp7_ = NULL;
#line 277 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp6_ = parsed;
#line 277 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp7_ = g_strconcat (_tmp6_, " ", NULL);
#line 277 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (parsed);
#line 277 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					parsed = _tmp7_;
#line 278 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (val);
#line 278 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (part);
#line 278 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					continue;
#line 1682 "TaskRow.c"
				}
#line 281 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				_tmp8_ = part;
#line 281 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				_tmp9_ = gofi_txt_utils_is_context_tag (_tmp8_);
#line 281 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				if (_tmp9_) {
#line 1690 "TaskRow.c"
					const gchar* _tmp10_ = NULL;
					gchar* _tmp11_ = NULL;
					gchar* _tmp12_ = NULL;
					const gchar* _tmp13_ = NULL;
					const gchar* _tmp14_ = NULL;
					gchar** _tmp15_ = NULL;
					gchar** _tmp16_ = NULL;
					gchar** _tmp17_ = NULL;
					gint _tmp17__length1 = 0;
					const gchar* _tmp18_ = NULL;
					gchar* _tmp19_ = NULL;
#line 282 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp10_ = _ ("context");
#line 282 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp11_ = g_strdup (_tmp10_);
#line 282 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (prefix);
#line 282 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					prefix = _tmp11_;
#line 283 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp12_ = g_strdup ("@");
#line 283 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (delimiter);
#line 283 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					delimiter = _tmp12_;
#line 284 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp13_ = part;
#line 284 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp14_ = delimiter;
#line 284 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp16_ = _tmp15_ = g_strsplit (_tmp13_, _tmp14_, 2);
#line 284 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp17_ = _tmp16_;
#line 284 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp17__length1 = _vala_array_length (_tmp15_);
#line 284 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp18_ = _tmp17_[1];
#line 284 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp19_ = g_strdup (_tmp18_);
#line 284 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (val);
#line 284 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					val = _tmp19_;
#line 284 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp17_ = (_vala_array_free (_tmp17_, _tmp17__length1, (GDestroyNotify) g_free), NULL);
#line 1736 "TaskRow.c"
				}
#line 286 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				_tmp20_ = part;
#line 286 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				_tmp21_ = gofi_txt_utils_is_project_tag (_tmp20_);
#line 286 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				if (_tmp21_) {
#line 1744 "TaskRow.c"
					const gchar* _tmp22_ = NULL;
					gchar* _tmp23_ = NULL;
					gchar* _tmp24_ = NULL;
					const gchar* _tmp25_ = NULL;
					const gchar* _tmp26_ = NULL;
					gchar** _tmp27_ = NULL;
					gchar** _tmp28_ = NULL;
					gchar** _tmp29_ = NULL;
					gint _tmp29__length1 = 0;
					const gchar* _tmp30_ = NULL;
					gchar* _tmp31_ = NULL;
#line 287 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp22_ = _ ("project");
#line 287 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp23_ = g_strdup (_tmp22_);
#line 287 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (prefix);
#line 287 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					prefix = _tmp23_;
#line 288 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp24_ = g_strdup ("+");
#line 288 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (delimiter);
#line 288 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					delimiter = _tmp24_;
#line 289 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp25_ = part;
#line 289 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp26_ = delimiter;
#line 289 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp28_ = _tmp27_ = g_strsplit (_tmp25_, _tmp26_, 2);
#line 289 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp29_ = _tmp28_;
#line 289 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp29__length1 = _vala_array_length (_tmp27_);
#line 289 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp30_ = _tmp29_[1];
#line 289 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp31_ = g_strdup (_tmp30_);
#line 289 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (val);
#line 289 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					val = _tmp31_;
#line 289 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp29_ = (_vala_array_free (_tmp29_, _tmp29__length1, (GDestroyNotify) g_free), NULL);
#line 1790 "TaskRow.c"
				}
#line 291 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				_tmp32_ = val;
#line 291 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				if (_tmp32_ != NULL) {
#line 1796 "TaskRow.c"
					const gchar* _tmp33_ = NULL;
					const gchar* _tmp34_ = NULL;
					const gchar* _tmp35_ = NULL;
					const gchar* _tmp36_ = NULL;
					const gchar* _tmp37_ = NULL;
					const gchar* _tmp38_ = NULL;
					const gchar* _tmp39_ = NULL;
					gchar* _tmp40_ = NULL;
					gchar* _tmp41_ = NULL;
					const gchar* _tmp42_ = NULL;
					const gchar* _tmp43_ = NULL;
					const gchar* _tmp44_ = NULL;
					const gchar* _tmp45_ = NULL;
					gchar* _tmp46_ = NULL;
					gchar* _tmp47_ = NULL;
					gchar* _tmp48_ = NULL;
					gchar* _tmp49_ = NULL;
					gchar* _tmp50_ = NULL;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp33_ = parsed;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp34_ = prefix;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp35_ = string_to_string (_tmp34_);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp36_ = val;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp37_ = string_to_string (_tmp36_);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp38_ = val;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp39_ = string_to_string (_tmp38_);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp40_ = g_strconcat (" <a href=\"", _tmp35_, ":", _tmp37_, "\" title=\"", _tmp39_, "\">", NULL);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp41_ = _tmp40_;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp42_ = delimiter;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp43_ = string_to_string (_tmp42_);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp44_ = val;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp45_ = string_to_string (_tmp44_);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp46_ = g_strconcat (_tmp43_, _tmp45_, "</a>", NULL);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp47_ = _tmp46_;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp48_ = g_strconcat (_tmp41_, _tmp47_, NULL);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp49_ = _tmp48_;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp50_ = g_strconcat (_tmp33_, _tmp49_, NULL);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (parsed);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					parsed = _tmp50_;
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (_tmp49_);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (_tmp47_);
#line 292 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (_tmp41_);
#line 1861 "TaskRow.c"
				} else {
					const gchar* _tmp51_ = NULL;
					const gchar* _tmp52_ = NULL;
					gchar* _tmp53_ = NULL;
					gchar* _tmp54_ = NULL;
					gchar* _tmp55_ = NULL;
#line 295 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp51_ = parsed;
#line 295 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp52_ = part;
#line 295 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp53_ = g_strconcat (" ", _tmp52_, NULL);
#line 295 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp54_ = _tmp53_;
#line 295 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_tmp55_ = g_strconcat (_tmp51_, _tmp54_, NULL);
#line 295 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (parsed);
#line 295 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					parsed = _tmp55_;
#line 295 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
					_g_free0 (_tmp54_);
#line 1884 "TaskRow.c"
				}
#line 274 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				_g_free0 (val);
#line 274 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
				_g_free0 (part);
#line 1890 "TaskRow.c"
			}
		}
#line 274 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		part_collection = (_vala_array_free (part_collection, part_collection_length1, (GDestroyNotify) g_free), NULL);
#line 1895 "TaskRow.c"
	}
#line 299 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp56_ = parsed;
#line 299 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp57_ = string_chug (_tmp56_);
#line 299 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	result = _tmp57_;
#line 299 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (prefix);
#line 299 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (delimiter);
#line 299 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (parsed);
#line 299 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	return result;
#line 1911 "TaskRow.c"
}


static void task_row_task_markup_label_update (TaskRowTaskMarkupLabel* self) {
	const gchar* _tmp0_ = NULL;
#line 302 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 303 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_markup_label_gen_markup (self);
#line 304 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->markup_string;
#line 304 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	gtk_label_set_markup ((GtkLabel*) self, _tmp0_);
#line 1925 "TaskRow.c"
}


static void _task_row_task_markup_label_update_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 308 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_markup_label_update ((TaskRowTaskMarkupLabel*) self);
#line 1932 "TaskRow.c"
}


static void task_row_task_markup_label_connect_signals (TaskRowTaskMarkupLabel* self) {
	TodoTask* _tmp0_ = NULL;
	TodoTask* _tmp1_ = NULL;
#line 307 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_return_if_fail (self != NULL);
#line 308 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp0_ = self->priv->task;
#line 308 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object ((GObject*) _tmp0_, "notify::description", (GCallback) _task_row_task_markup_label_update_g_object_notify, self, 0);
#line 309 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_tmp1_ = self->priv->task;
#line 309 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_connect_object ((GObject*) _tmp1_, "notify::priority", (GCallback) _task_row_task_markup_label_update_g_object_notify, self, 0);
#line 1949 "TaskRow.c"
}


static void task_row_task_markup_label_class_init (TaskRowTaskMarkupLabelClass * klass) {
#line 208 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_task_markup_label_parent_class = g_type_class_peek_parent (klass);
#line 208 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_type_class_add_private (klass, sizeof (TaskRowTaskMarkupLabelPrivate));
#line 208 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	G_OBJECT_CLASS (klass)->finalize = task_row_task_markup_label_finalize;
#line 1960 "TaskRow.c"
}


static void task_row_task_markup_label_instance_init (TaskRowTaskMarkupLabel * self) {
#line 208 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv = TASK_ROW_TASK_MARKUP_LABEL_GET_PRIVATE (self);
#line 1967 "TaskRow.c"
}


static void task_row_task_markup_label_finalize (GObject* obj) {
	TaskRowTaskMarkupLabel * self;
#line 208 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TASK_ROW_TYPE_TASK_MARKUP_LABEL, TaskRowTaskMarkupLabel);
#line 209 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->task);
#line 211 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_free0 (self->priv->markup_string);
#line 208 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	G_OBJECT_CLASS (task_row_task_markup_label_parent_class)->finalize (obj);
#line 1981 "TaskRow.c"
}


static GType task_row_task_markup_label_get_type (void) {
	static volatile gsize task_row_task_markup_label_type_id__volatile = 0;
	if (g_once_init_enter (&task_row_task_markup_label_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TaskRowTaskMarkupLabelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) task_row_task_markup_label_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TaskRowTaskMarkupLabel), 0, (GInstanceInitFunc) task_row_task_markup_label_instance_init, NULL };
		GType task_row_task_markup_label_type_id;
		task_row_task_markup_label_type_id = g_type_register_static (gtk_label_get_type (), "TaskRowTaskMarkupLabel", &g_define_type_info, 0);
		g_once_init_leave (&task_row_task_markup_label_type_id__volatile, task_row_task_markup_label_type_id);
	}
	return task_row_task_markup_label_type_id__volatile;
}


static void task_row_class_init (TaskRowClass * klass) {
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	task_row_parent_class = g_type_class_peek_parent (klass);
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_type_class_add_private (klass, sizeof (TaskRowPrivate));
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_task_row_get_property;
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_task_row_set_property;
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	G_OBJECT_CLASS (klass)->finalize = task_row_finalize;
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), TASK_ROW_TASK, g_param_spec_object ("task", "task", "task", TYPE_TODO_TASK, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_new ("link_clicked", TYPE_TASK_ROW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	g_signal_new ("deletion_requested", TYPE_TASK_ROW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 2014 "TaskRow.c"
}


static void task_row_instance_init (TaskRow * self) {
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self->priv = TASK_ROW_GET_PRIVATE (self);
#line 2021 "TaskRow.c"
}


static void task_row_finalize (GObject* obj) {
	TaskRow * self;
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TASK_ROW, TaskRow);
#line 21 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->check_button);
#line 22 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->delete_button);
#line 23 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->markup_label);
#line 24 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->edit_entry);
#line 28 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	_g_object_unref0 (self->priv->_task);
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	G_OBJECT_CLASS (task_row_parent_class)->finalize (obj);
#line 2041 "TaskRow.c"
}


GType task_row_get_type (void) {
	static volatile gsize task_row_type_id__volatile = 0;
	if (g_once_init_enter (&task_row_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TaskRowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) task_row_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TaskRow), 0, (GInstanceInitFunc) task_row_instance_init, NULL };
		GType task_row_type_id;
		task_row_type_id = g_type_register_static (TYPE_DRAG_LIST_ROW, "TaskRow", &g_define_type_info, 0);
		g_once_init_leave (&task_row_type_id__volatile, task_row_type_id);
	}
	return task_row_type_id__volatile;
}


static void _vala_task_row_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TaskRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_TASK_ROW, TaskRow);
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	switch (property_id) {
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		case TASK_ROW_TASK:
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		g_value_set_object (value, task_row_get_task (self));
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		break;
#line 2068 "TaskRow.c"
		default:
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		break;
#line 2074 "TaskRow.c"
	}
}


static void _vala_task_row_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TaskRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_TASK_ROW, TaskRow);
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
	switch (property_id) {
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		case TASK_ROW_TASK:
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		task_row_set_task (self, g_value_get_object (value));
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		break;
#line 2090 "TaskRow.c"
		default:
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "/home/mark/projects/Go-For-It/src/view/TaskRow.vala"
		break;
#line 2096 "TaskRow.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



