/* TaskTimer.c generated by valac 0.34.7, the Vala compiler
 * generated from TaskTimer.vala, do not modify */

/* Copyright 2014-2017 Go For It! developers
*
* This file is part of Go For It!.
*
* Go For It! is free software: you can redistribute it
* and/or modify it under the terms of version 3 of the
* GNU General Public License as published by the Free Software Foundation.
*
* Go For It! is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Go For It!. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define TYPE_TASK_TIMER (task_timer_get_type ())
#define TASK_TIMER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TASK_TIMER, TaskTimer))
#define TASK_TIMER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TASK_TIMER, TaskTimerClass))
#define IS_TASK_TIMER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TASK_TIMER))
#define IS_TASK_TIMER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TASK_TIMER))
#define TASK_TIMER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TASK_TIMER, TaskTimerClass))

typedef struct _TaskTimer TaskTimer;
typedef struct _TaskTimerClass TaskTimerClass;
typedef struct _TaskTimerPrivate TaskTimerPrivate;

#define TYPE_SETTINGS_MANAGER (settings_manager_get_type ())
#define SETTINGS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SETTINGS_MANAGER, SettingsManager))
#define SETTINGS_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SETTINGS_MANAGER, SettingsManagerClass))
#define IS_SETTINGS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SETTINGS_MANAGER))
#define IS_SETTINGS_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SETTINGS_MANAGER))
#define SETTINGS_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SETTINGS_MANAGER, SettingsManagerClass))

typedef struct _SettingsManager SettingsManager;
typedef struct _SettingsManagerClass SettingsManagerClass;

#define TYPE_TODO_TASK (todo_task_get_type ())
#define TODO_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TODO_TASK, TodoTask))
#define TODO_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TODO_TASK, TodoTaskClass))
#define IS_TODO_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TODO_TASK))
#define IS_TODO_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TODO_TASK))
#define TODO_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TODO_TASK, TodoTaskClass))

typedef struct _TodoTask TodoTask;
typedef struct _TodoTaskClass TodoTaskClass;
#define _settings_manager_unref0(var) ((var == NULL) ? NULL : (var = (settings_manager_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ParamSpecTaskTimer ParamSpecTaskTimer;

struct _TaskTimer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TaskTimerPrivate * priv;
	GDateTime* start_time;
};

struct _TaskTimerClass {
	GTypeClass parent_class;
	void (*finalize) (TaskTimer *self);
};

struct _TaskTimerPrivate {
	SettingsManager* settings;
	gboolean _running;
	gboolean _break_active;
	GDateTime* duration_till_end;
	gint64 _previous_runtime;
	TodoTask* _active_task;
	gboolean _almost_over_sent_already;
};

struct _ParamSpecTaskTimer {
	GParamSpec parent_instance;
};


static gpointer task_timer_parent_class = NULL;

gpointer task_timer_ref (gpointer instance);
void task_timer_unref (gpointer instance);
GParamSpec* param_spec_task_timer (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_task_timer (GValue* value, gpointer v_object);
void value_take_task_timer (GValue* value, gpointer v_object);
gpointer value_get_task_timer (const GValue* value);
GType task_timer_get_type (void) G_GNUC_CONST;
gpointer settings_manager_ref (gpointer instance);
void settings_manager_unref (gpointer instance);
GParamSpec* param_spec_settings_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_settings_manager (GValue* value, gpointer v_object);
void value_take_settings_manager (GValue* value, gpointer v_object);
gpointer value_get_settings_manager (const GValue* value);
GType settings_manager_get_type (void) G_GNUC_CONST;
GType todo_task_get_type (void) G_GNUC_CONST;
#define TASK_TIMER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TASK_TIMER, TaskTimerPrivate))
enum  {
	TASK_TIMER_DUMMY_PROPERTY
};
TaskTimer* task_timer_new (SettingsManager* settings);
TaskTimer* task_timer_construct (GType object_type, SettingsManager* settings);
static void __lambda5_ (TaskTimer* self, SettingsManager* e);
gboolean task_timer_get_running (TaskTimer* self);
void task_timer_reset (TaskTimer* self);
static void ___lambda5__settings_manager_timer_duration_changed (SettingsManager* _sender, gpointer self);
static gboolean __lambda6_ (TaskTimer* self);
static gboolean task_timer_has_finished (TaskTimer* self);
void task_timer_end_iteration (TaskTimer* self);
void task_timer_update (TaskTimer* self);
static gboolean ___lambda6__gsource_func (gpointer self);
void task_timer_start (TaskTimer* self);
TodoTask* task_timer_get_active_task (TaskTimer* self);
static void task_timer_set_running (TaskTimer* self, gboolean value);
void task_timer_stop (TaskTimer* self);
GDateTime* task_timer_get_remaining_duration (TaskTimer* self);
static gint64 task_timer_get_previous_runtime (TaskTimer* self);
GDateTime* task_timer_get_runtime (TaskTimer* self);
static void task_timer_set_previous_runtime (TaskTimer* self, gint64 value);
gboolean task_timer_get_break_active (TaskTimer* self);
gint settings_manager_get_break_duration (SettingsManager* self);
gint settings_manager_get_task_duration (SettingsManager* self);
gint settings_manager_get_reminder_time (SettingsManager* self);
gboolean settings_manager_get_reminder_active (SettingsManager* self);
static gboolean task_timer_get_almost_over_sent_already (TaskTimer* self);
static void task_timer_set_almost_over_sent_already (TaskTimer* self, gboolean value);
void task_timer_update_active_task (TaskTimer* self);
static void task_timer_on_task_notify_description (TaskTimer* self);
void task_timer_set_active_task_done (TaskTimer* self);
void task_timer_toggle_break (TaskTimer* self);
static void task_timer_set_break_active (TaskTimer* self, gboolean value);
void task_timer_set_remaining_duration (TaskTimer* self, GDateTime* value);
void task_timer_set_active_task (TaskTimer* self, TodoTask* value);
static void _task_timer_on_task_notify_description_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void g_cclosure_user_marshal_VOID__OBJECT_BOOLEAN (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void task_timer_finalize (TaskTimer* obj);


static gpointer _settings_manager_ref0 (gpointer self) {
#line 82 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return self ? settings_manager_ref (self) : NULL;
#line 153 "TaskTimer.c"
}


static void __lambda5_ (TaskTimer* self, SettingsManager* e) {
	gboolean _tmp0_ = FALSE;
#line 84 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (e != NULL);
#line 85 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_running;
#line 85 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (!_tmp0_) {
#line 86 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_reset (self);
#line 167 "TaskTimer.c"
	}
}


static void ___lambda5__settings_manager_timer_duration_changed (SettingsManager* _sender, gpointer self) {
#line 84 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	__lambda5_ ((TaskTimer*) self, _sender);
#line 175 "TaskTimer.c"
}


static gboolean __lambda6_ (TaskTimer* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
#line 96 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_running;
#line 96 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (_tmp0_) {
#line 186 "TaskTimer.c"
		gboolean _tmp1_ = FALSE;
#line 97 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp1_ = task_timer_has_finished (self);
#line 97 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		if (_tmp1_) {
#line 98 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			task_timer_end_iteration (self);
#line 194 "TaskTimer.c"
		}
#line 100 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_update (self);
#line 198 "TaskTimer.c"
	}
#line 103 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	result = TRUE;
#line 103 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return result;
#line 204 "TaskTimer.c"
}


static gboolean ___lambda6__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda6_ ((TaskTimer*) self);
#line 95 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return result;
#line 213 "TaskTimer.c"
}


TaskTimer* task_timer_construct (GType object_type, SettingsManager* settings) {
	TaskTimer* self = NULL;
	SettingsManager* _tmp0_ = NULL;
	SettingsManager* _tmp1_ = NULL;
	SettingsManager* _tmp2_ = NULL;
#line 81 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (settings != NULL, NULL);
#line 81 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self = (TaskTimer*) g_type_create_instance (object_type);
#line 82 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = settings;
#line 82 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp1_ = _settings_manager_ref0 (_tmp0_);
#line 82 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_settings_manager_unref0 (self->priv->settings);
#line 82 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->settings = _tmp1_;
#line 84 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp2_ = settings;
#line 84 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_connect (_tmp2_, "timer-duration-changed", (GCallback) ___lambda5__settings_manager_timer_duration_changed, self);
#line 95 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 500, ___lambda6__gsource_func, task_timer_ref (self), task_timer_unref);
#line 105 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_reset (self);
#line 81 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return self;
#line 244 "TaskTimer.c"
}


TaskTimer* task_timer_new (SettingsManager* settings) {
#line 81 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return task_timer_construct (TYPE_TASK_TIMER, settings);
#line 251 "TaskTimer.c"
}


void task_timer_start (TaskTimer* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
#line 108 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 109 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp1_ = self->priv->_running;
#line 109 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (!_tmp1_) {
#line 264 "TaskTimer.c"
		TodoTask* _tmp2_ = NULL;
		TodoTask* _tmp3_ = NULL;
#line 109 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp2_ = task_timer_get_active_task (self);
#line 109 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp3_ = _tmp2_;
#line 109 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp0_ = _tmp3_ != NULL;
#line 273 "TaskTimer.c"
	} else {
#line 109 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp0_ = FALSE;
#line 277 "TaskTimer.c"
	}
#line 109 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (_tmp0_) {
#line 281 "TaskTimer.c"
		GDateTime* _tmp4_ = NULL;
		gboolean _tmp5_ = FALSE;
#line 110 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp4_ = g_date_time_new_now_utc ();
#line 110 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_g_date_time_unref0 (self->start_time);
#line 110 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		self->start_time = _tmp4_;
#line 111 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_set_running (self, TRUE);
#line 112 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp5_ = self->priv->_running;
#line 112 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		g_signal_emit_by_name (self, "timer-running-changed", _tmp5_);
#line 296 "TaskTimer.c"
	}
}


void task_timer_stop (TaskTimer* self) {
	gboolean _tmp0_ = FALSE;
#line 116 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 117 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_running;
#line 117 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (_tmp0_) {
#line 309 "TaskTimer.c"
		GDateTime* _tmp1_ = NULL;
		GDateTime* _tmp2_ = NULL;
		gint64 _tmp3_ = 0LL;
		GDateTime* _tmp4_ = NULL;
		GDateTime* _tmp5_ = NULL;
		gint64 _tmp6_ = 0LL;
		gboolean _tmp7_ = FALSE;
#line 118 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp1_ = task_timer_get_remaining_duration (self);
#line 118 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp2_ = _tmp1_;
#line 118 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_g_date_time_unref0 (self->priv->duration_till_end);
#line 118 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		self->priv->duration_till_end = _tmp2_;
#line 119 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp3_ = self->priv->_previous_runtime;
#line 119 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp4_ = task_timer_get_runtime (self);
#line 119 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp5_ = _tmp4_;
#line 119 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp6_ = g_date_time_to_unix (_tmp5_);
#line 119 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_set_previous_runtime (self, _tmp3_ + _tmp6_);
#line 119 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_g_date_time_unref0 (_tmp5_);
#line 120 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_set_running (self, FALSE);
#line 121 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp7_ = self->priv->_running;
#line 121 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		g_signal_emit_by_name (self, "timer-running-changed", _tmp7_);
#line 343 "TaskTimer.c"
	}
}


void task_timer_reset (TaskTimer* self) {
	gint64 default_duration = 0LL;
	gboolean _tmp0_ = FALSE;
	gint64 _tmp7_ = 0LL;
	GDateTime* _tmp8_ = NULL;
#line 125 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 127 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_break_active;
#line 127 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (_tmp0_) {
#line 359 "TaskTimer.c"
		SettingsManager* _tmp1_ = NULL;
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
#line 128 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp1_ = self->priv->settings;
#line 128 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp2_ = settings_manager_get_break_duration (_tmp1_);
#line 128 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp3_ = _tmp2_;
#line 128 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		default_duration = (gint64) _tmp3_;
#line 371 "TaskTimer.c"
	} else {
		SettingsManager* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
#line 130 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp4_ = self->priv->settings;
#line 130 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp5_ = settings_manager_get_task_duration (_tmp4_);
#line 130 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp6_ = _tmp5_;
#line 130 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		default_duration = (gint64) _tmp6_;
#line 384 "TaskTimer.c"
	}
#line 132 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp7_ = default_duration;
#line 132 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp8_ = g_date_time_new_from_unix_utc (_tmp7_);
#line 132 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_date_time_unref0 (self->priv->duration_till_end);
#line 132 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->duration_till_end = _tmp8_;
#line 133 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_set_previous_runtime (self, (gint64) 0);
#line 134 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_update (self);
#line 398 "TaskTimer.c"
}


/**
     * Used to initiate a timer_updated signal from outside of this class.
     */
void task_timer_update (TaskTimer* self) {
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	GDateTime* _tmp2_ = NULL;
	gdouble runtime = 0.0;
	GDateTime* _tmp3_ = NULL;
	GDateTime* _tmp4_ = NULL;
	gint64 _tmp5_ = 0LL;
	gint64 _tmp6_ = 0LL;
	gdouble _tmp7_ = 0.0;
	gdouble total = 0.0;
	GDateTime* _tmp8_ = NULL;
	gint64 _tmp9_ = 0LL;
	gint64 _tmp10_ = 0LL;
	gdouble progress = 0.0;
	gdouble _tmp11_ = 0.0;
	gdouble _tmp12_ = 0.0;
	gdouble _tmp13_ = 0.0;
	GDateTime* _tmp14_ = NULL;
	GDateTime* _tmp15_ = NULL;
	GDateTime* _tmp16_ = NULL;
	gint64 _tmp17_ = 0LL;
	SettingsManager* _tmp18_ = NULL;
	gint _tmp19_ = 0;
	gint _tmp20_ = 0;
	gboolean _tmp21_ = FALSE;
#line 140 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 141 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = task_timer_get_remaining_duration (self);
#line 141 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp1_ = _tmp0_;
#line 141 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp2_ = _tmp1_;
#line 141 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_emit_by_name (self, "timer-updated", _tmp2_);
#line 141 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_date_time_unref0 (_tmp2_);
#line 143 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp3_ = task_timer_get_runtime (self);
#line 143 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp4_ = _tmp3_;
#line 143 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp5_ = g_date_time_to_unix (_tmp4_);
#line 143 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp6_ = self->priv->_previous_runtime;
#line 143 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp7_ = (gdouble) (_tmp5_ + _tmp6_);
#line 143 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_date_time_unref0 (_tmp4_);
#line 143 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	runtime = _tmp7_;
#line 145 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp8_ = self->priv->duration_till_end;
#line 145 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp9_ = g_date_time_to_unix (_tmp8_);
#line 145 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp10_ = self->priv->_previous_runtime;
#line 145 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	total = (gdouble) (_tmp9_ + _tmp10_);
#line 147 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp11_ = runtime;
#line 147 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp12_ = total;
#line 147 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	progress = _tmp11_ / _tmp12_;
#line 148 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp13_ = progress;
#line 148 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_emit_by_name (self, "timer-updated-relative", _tmp13_);
#line 151 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp14_ = task_timer_get_remaining_duration (self);
#line 151 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp15_ = _tmp14_;
#line 151 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp16_ = _tmp15_;
#line 151 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp17_ = g_date_time_to_unix (_tmp16_);
#line 151 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp18_ = self->priv->settings;
#line 151 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp19_ = settings_manager_get_reminder_time (_tmp18_);
#line 151 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp20_ = _tmp19_;
#line 151 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp21_ = _tmp17_ <= ((gint64) _tmp20_);
#line 151 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_date_time_unref0 (_tmp16_);
#line 151 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (_tmp21_) {
#line 495 "TaskTimer.c"
		gboolean _tmp22_ = FALSE;
		gboolean _tmp23_ = FALSE;
		gboolean _tmp24_ = FALSE;
		SettingsManager* _tmp25_ = NULL;
		gboolean _tmp26_ = FALSE;
		gboolean _tmp27_ = FALSE;
#line 152 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp25_ = self->priv->settings;
#line 152 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp26_ = settings_manager_get_reminder_active (_tmp25_);
#line 152 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp27_ = _tmp26_;
#line 152 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		if (_tmp27_) {
#line 510 "TaskTimer.c"
			gboolean _tmp28_ = FALSE;
#line 153 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp28_ = self->priv->_almost_over_sent_already;
#line 153 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp24_ = !_tmp28_;
#line 516 "TaskTimer.c"
		} else {
#line 152 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp24_ = FALSE;
#line 520 "TaskTimer.c"
		}
#line 152 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		if (_tmp24_) {
#line 524 "TaskTimer.c"
			gboolean _tmp29_ = FALSE;
#line 154 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp29_ = self->priv->_running;
#line 154 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp23_ = _tmp29_;
#line 530 "TaskTimer.c"
		} else {
#line 152 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp23_ = FALSE;
#line 534 "TaskTimer.c"
		}
#line 152 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		if (_tmp23_) {
#line 538 "TaskTimer.c"
			gboolean _tmp30_ = FALSE;
#line 155 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp30_ = self->priv->_break_active;
#line 155 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp22_ = !_tmp30_;
#line 544 "TaskTimer.c"
		} else {
#line 152 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp22_ = FALSE;
#line 548 "TaskTimer.c"
		}
#line 152 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		if (_tmp22_) {
#line 552 "TaskTimer.c"
			GDateTime* _tmp31_ = NULL;
			GDateTime* _tmp32_ = NULL;
			GDateTime* _tmp33_ = NULL;
#line 157 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp31_ = task_timer_get_remaining_duration (self);
#line 157 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp32_ = _tmp31_;
#line 157 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_tmp33_ = _tmp32_;
#line 157 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			g_signal_emit_by_name (self, "timer-almost-over", _tmp33_);
#line 157 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			_g_date_time_unref0 (_tmp33_);
#line 158 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			task_timer_set_almost_over_sent_already (self, TRUE);
#line 568 "TaskTimer.c"
		}
	} else {
#line 161 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_set_almost_over_sent_already (self, FALSE);
#line 573 "TaskTimer.c"
	}
}


/**
     * Used to initate an active_task_changed signal
     */
void task_timer_update_active_task (TaskTimer* self) {
	TodoTask* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 168 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 169 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_active_task;
#line 169 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp1_ = self->priv->_break_active;
#line 169 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_emit_by_name (self, "active-task-changed", _tmp0_, _tmp1_);
#line 592 "TaskTimer.c"
}


static void task_timer_on_task_notify_description (TaskTimer* self) {
	TodoTask* _tmp0_ = NULL;
#line 172 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 173 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_active_task;
#line 173 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_emit_by_name (self, "active-task-description-changed", _tmp0_);
#line 604 "TaskTimer.c"
}


/**
     * Used to emit an "active_task_done" signal from outside of this class.
     */
void task_timer_set_active_task_done (TaskTimer* self) {
	TodoTask* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 179 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 180 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_stop (self);
#line 181 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_active_task;
#line 181 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_emit_by_name (self, "active-task-done", _tmp0_);
#line 183 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp1_ = self->priv->_break_active;
#line 183 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (_tmp1_) {
#line 184 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_start (self);
#line 628 "TaskTimer.c"
	}
}


/**
     * Determines if the running timer has finished, according to runtime and
     * duration.
     */
static gboolean task_timer_has_finished (TaskTimer* self) {
	gboolean result = FALSE;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	GDateTime* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gboolean _tmp4_ = FALSE;
#line 192 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 193 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = task_timer_get_runtime (self);
#line 193 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp1_ = _tmp0_;
#line 193 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp2_ = self->priv->duration_till_end;
#line 193 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp3_ = g_date_time_compare (_tmp1_, _tmp2_);
#line 193 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp4_ = _tmp3_ >= 0;
#line 193 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_date_time_unref0 (_tmp1_);
#line 193 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	result = _tmp4_;
#line 193 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return result;
#line 662 "TaskTimer.c"
}


GDateTime* task_timer_get_runtime (TaskTimer* self) {
	GDateTime* result = NULL;
	gboolean _tmp0_ = FALSE;
#line 196 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 197 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_running;
#line 197 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (_tmp0_) {
#line 675 "TaskTimer.c"
		GTimeSpan diff = 0LL;
		GDateTime* _tmp1_ = NULL;
		GDateTime* _tmp2_ = NULL;
		GDateTime* _tmp3_ = NULL;
		GTimeSpan _tmp4_ = 0LL;
		GTimeSpan _tmp5_ = 0LL;
		GDateTime* _tmp6_ = NULL;
		GDateTime* _tmp7_ = NULL;
		GTimeSpan _tmp8_ = 0LL;
		GDateTime* _tmp9_ = NULL;
		GDateTime* _tmp10_ = NULL;
#line 198 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp1_ = g_date_time_new_now_utc ();
#line 198 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp2_ = _tmp1_;
#line 198 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp3_ = self->start_time;
#line 198 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp4_ = g_date_time_difference (_tmp2_, _tmp3_);
#line 198 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp5_ = _tmp4_;
#line 198 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_g_date_time_unref0 (_tmp2_);
#line 198 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		diff = _tmp5_;
#line 199 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp6_ = g_date_time_new_from_unix_utc ((gint64) 0);
#line 199 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp7_ = _tmp6_;
#line 199 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp8_ = diff;
#line 199 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp9_ = g_date_time_add (_tmp7_, _tmp8_);
#line 199 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp10_ = _tmp9_;
#line 199 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_g_date_time_unref0 (_tmp7_);
#line 199 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		result = _tmp10_;
#line 199 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		return result;
#line 717 "TaskTimer.c"
	} else {
		GDateTime* _tmp11_ = NULL;
#line 201 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp11_ = g_date_time_new_from_unix_utc ((gint64) 0);
#line 201 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		result = _tmp11_;
#line 201 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		return result;
#line 726 "TaskTimer.c"
	}
}


/**
     * Used to toggle between break and work state.
     */
void task_timer_toggle_break (TaskTimer* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	TodoTask* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
#line 208 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 209 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_break_active;
#line 209 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_set_break_active (self, !_tmp0_);
#line 210 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_reset (self);
#line 211 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp1_ = self->priv->_break_active;
#line 211 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (_tmp1_) {
#line 212 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_start (self);
#line 753 "TaskTimer.c"
	}
#line 214 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp2_ = self->priv->_active_task;
#line 214 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp3_ = self->priv->_break_active;
#line 214 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_emit_by_name (self, "active-task-changed", _tmp2_, _tmp3_);
#line 761 "TaskTimer.c"
}


/**
     * Ends the current iteration of the timer (either active task or break)
     * Is to be executed when the timer finishes, or skip has been initiated.
     * Handles switchting between breaks and active tasks as well as
     * emitting all corresponding signals.
     */
void task_timer_end_iteration (TaskTimer* self) {
	gboolean _tmp0_ = FALSE;
#line 223 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 225 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_break_active;
#line 225 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_emit_by_name (self, "timer-finished", _tmp0_);
#line 226 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_stop (self);
#line 227 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_toggle_break (self);
#line 783 "TaskTimer.c"
}


gboolean task_timer_get_running (TaskTimer* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 23 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 23 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_running;
#line 23 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	result = _tmp0_;
#line 23 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return result;
#line 798 "TaskTimer.c"
}


static void task_timer_set_running (TaskTimer* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
#line 23 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 23 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = value;
#line 23 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->_running = _tmp0_;
#line 810 "TaskTimer.c"
}


gboolean task_timer_get_break_active (TaskTimer* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 24 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 24 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_break_active;
#line 24 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	result = _tmp0_;
#line 24 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return result;
#line 825 "TaskTimer.c"
}


static void task_timer_set_break_active (TaskTimer* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
#line 24 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 24 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = value;
#line 24 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->_break_active = _tmp0_;
#line 837 "TaskTimer.c"
}


GDateTime* task_timer_get_remaining_duration (TaskTimer* self) {
	GDateTime* result;
	GTimeSpan diff = 0LL;
	GDateTime* _tmp0_ = NULL;
	GDateTime* _tmp1_ = NULL;
	GDateTime* _tmp2_ = NULL;
	GTimeSpan _tmp3_ = 0LL;
	GTimeSpan _tmp4_ = 0LL;
	GDateTime* _tmp5_ = NULL;
	GDateTime* _tmp6_ = NULL;
	GDateTime* _tmp7_ = NULL;
	GDateTime* _tmp8_ = NULL;
#line 35 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 36 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->duration_till_end;
#line 36 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp1_ = task_timer_get_runtime (self);
#line 36 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp2_ = _tmp1_;
#line 36 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp3_ = g_date_time_difference (_tmp0_, _tmp2_);
#line 36 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp4_ = _tmp3_;
#line 36 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_date_time_unref0 (_tmp2_);
#line 36 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	diff = _tmp4_;
#line 37 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp5_ = g_date_time_new_from_unix_utc ((gint64) 0);
#line 37 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp6_ = _tmp5_;
#line 37 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp7_ = g_date_time_add (_tmp6_, diff);
#line 37 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp8_ = _tmp7_;
#line 37 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_date_time_unref0 (_tmp6_);
#line 37 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	result = _tmp8_;
#line 37 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return result;
#line 883 "TaskTimer.c"
}


void task_timer_set_remaining_duration (TaskTimer* self, GDateTime* value) {
	gboolean _tmp0_ = FALSE;
#line 39 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 41 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_running;
#line 41 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (!_tmp0_) {
#line 895 "TaskTimer.c"
		GTimeSpan diff = 0LL;
		GDateTime* _tmp1_ = NULL;
		GDateTime* _tmp2_ = NULL;
		GDateTime* _tmp3_ = NULL;
		GDateTime* _tmp4_ = NULL;
		GTimeSpan _tmp5_ = 0LL;
		GTimeSpan _tmp6_ = 0LL;
		GDateTime* _tmp7_ = NULL;
		GTimeSpan _tmp8_ = 0LL;
		GDateTime* _tmp9_ = NULL;
#line 42 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp1_ = value;
#line 42 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp2_ = task_timer_get_remaining_duration (self);
#line 42 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp3_ = _tmp2_;
#line 42 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp4_ = _tmp3_;
#line 42 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp5_ = g_date_time_difference (_tmp1_, _tmp4_);
#line 42 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp6_ = _tmp5_;
#line 42 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_g_date_time_unref0 (_tmp4_);
#line 42 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		diff = _tmp6_;
#line 43 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp7_ = self->priv->duration_till_end;
#line 43 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp8_ = diff;
#line 43 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp9_ = g_date_time_add (_tmp7_, _tmp8_);
#line 43 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_g_date_time_unref0 (self->priv->duration_till_end);
#line 43 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		self->priv->duration_till_end = _tmp9_;
#line 44 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_update (self);
#line 934 "TaskTimer.c"
	}
}


static gint64 task_timer_get_previous_runtime (TaskTimer* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
#line 49 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (self != NULL, 0LL);
#line 49 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_previous_runtime;
#line 49 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	result = _tmp0_;
#line 49 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return result;
#line 950 "TaskTimer.c"
}


static void task_timer_set_previous_runtime (TaskTimer* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
#line 49 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 49 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = value;
#line 49 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->_previous_runtime = _tmp0_;
#line 962 "TaskTimer.c"
}


TodoTask* task_timer_get_active_task (TaskTimer* self) {
	TodoTask* result;
	TodoTask* _tmp0_ = NULL;
#line 52 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 52 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_active_task;
#line 52 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	result = _tmp0_;
#line 52 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return result;
#line 977 "TaskTimer.c"
}


static void _task_timer_on_task_notify_description_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 58 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_on_task_notify_description ((TaskTimer*) self);
#line 984 "TaskTimer.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 60 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return self ? g_object_ref (self) : NULL;
#line 991 "TaskTimer.c"
}


void task_timer_set_active_task (TaskTimer* self, TodoTask* value) {
	TodoTask* _tmp0_ = NULL;
	TodoTask* _tmp4_ = NULL;
	TodoTask* _tmp5_ = NULL;
	TodoTask* _tmp6_ = NULL;
#line 53 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 54 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_stop (self);
#line 55 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_reset (self);
#line 57 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_active_task;
#line 57 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (_tmp0_ != NULL) {
#line 1010 "TaskTimer.c"
		TodoTask* _tmp1_ = NULL;
		guint _tmp2_ = 0U;
		GQuark _tmp3_ = 0U;
#line 58 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp1_ = self->priv->_active_task;
#line 58 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		g_signal_parse_name ("notify::description", G_TYPE_OBJECT, &_tmp2_, &_tmp3_, TRUE);
#line 58 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		g_signal_handlers_disconnect_matched ((GObject*) _tmp1_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_DETAIL | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp2_, _tmp3_, NULL, (GCallback) _task_timer_on_task_notify_description_g_object_notify, self);
#line 1020 "TaskTimer.c"
	}
#line 60 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp4_ = value;
#line 60 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 60 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_object_unref0 (self->priv->_active_task);
#line 60 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->_active_task = _tmp5_;
#line 61 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp6_ = self->priv->_active_task;
#line 61 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (_tmp6_ != NULL) {
#line 1034 "TaskTimer.c"
		TodoTask* _tmp7_ = NULL;
#line 62 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		_tmp7_ = self->priv->_active_task;
#line 62 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		g_signal_connect ((GObject*) _tmp7_, "notify::description", (GCallback) _task_timer_on_task_notify_description_g_object_notify, self);
#line 1040 "TaskTimer.c"
	}
#line 66 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_update_active_task (self);
#line 1044 "TaskTimer.c"
}


static gboolean task_timer_get_almost_over_sent_already (TaskTimer* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 69 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 69 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = self->priv->_almost_over_sent_already;
#line 69 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	result = _tmp0_;
#line 69 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return result;
#line 1059 "TaskTimer.c"
}


static void task_timer_set_almost_over_sent_already (TaskTimer* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
#line 69 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (self != NULL);
#line 69 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_tmp0_ = value;
#line 69 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->_almost_over_sent_already = _tmp0_;
#line 1071 "TaskTimer.c"
}


static void g_cclosure_user_marshal_VOID__OBJECT_BOOLEAN (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__OBJECT_BOOLEAN) (gpointer data1, gpointer arg_1, gboolean arg_2, gpointer data2);
	register GMarshalFunc_VOID__OBJECT_BOOLEAN callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (n_param_values == 3);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		data1 = closure->data;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		data2 = param_values->data[0].v_pointer;
#line 1090 "TaskTimer.c"
	} else {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		data1 = param_values->data[0].v_pointer;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		data2 = closure->data;
#line 1096 "TaskTimer.c"
	}
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	callback = (GMarshalFunc_VOID__OBJECT_BOOLEAN) (marshal_data ? marshal_data : cc->callback);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	callback (data1, g_value_get_object (param_values + 1), g_value_get_boolean (param_values + 2), data2);
#line 1102 "TaskTimer.c"
}


static void value_task_timer_init (GValue* value) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	value->data[0].v_pointer = NULL;
#line 1109 "TaskTimer.c"
}


static void value_task_timer_free_value (GValue* value) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (value->data[0].v_pointer) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_unref (value->data[0].v_pointer);
#line 1118 "TaskTimer.c"
	}
}


static void value_task_timer_copy_value (const GValue* src_value, GValue* dest_value) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (src_value->data[0].v_pointer) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		dest_value->data[0].v_pointer = task_timer_ref (src_value->data[0].v_pointer);
#line 1128 "TaskTimer.c"
	} else {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		dest_value->data[0].v_pointer = NULL;
#line 1132 "TaskTimer.c"
	}
}


static gpointer value_task_timer_peek_pointer (const GValue* value) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return value->data[0].v_pointer;
#line 1140 "TaskTimer.c"
}


static gchar* value_task_timer_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (collect_values[0].v_pointer) {
#line 1147 "TaskTimer.c"
		TaskTimer* object;
		object = collect_values[0].v_pointer;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		if (object->parent_instance.g_class == NULL) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1154 "TaskTimer.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1158 "TaskTimer.c"
		}
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		value->data[0].v_pointer = task_timer_ref (object);
#line 1162 "TaskTimer.c"
	} else {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		value->data[0].v_pointer = NULL;
#line 1166 "TaskTimer.c"
	}
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return NULL;
#line 1170 "TaskTimer.c"
}


static gchar* value_task_timer_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TaskTimer** object_p;
	object_p = collect_values[0].v_pointer;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (!object_p) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 1181 "TaskTimer.c"
	}
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (!value->data[0].v_pointer) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		*object_p = NULL;
#line 1187 "TaskTimer.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		*object_p = value->data[0].v_pointer;
#line 1191 "TaskTimer.c"
	} else {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		*object_p = task_timer_ref (value->data[0].v_pointer);
#line 1195 "TaskTimer.c"
	}
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return NULL;
#line 1199 "TaskTimer.c"
}


GParamSpec* param_spec_task_timer (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecTaskTimer* spec;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_TASK_TIMER), NULL);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return G_PARAM_SPEC (spec);
#line 1213 "TaskTimer.c"
}


gpointer value_get_task_timer (const GValue* value) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TASK_TIMER), NULL);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return value->data[0].v_pointer;
#line 1222 "TaskTimer.c"
}


void value_set_task_timer (GValue* value, gpointer v_object) {
	TaskTimer* old;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TASK_TIMER));
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	old = value->data[0].v_pointer;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (v_object) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_TASK_TIMER));
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		value->data[0].v_pointer = v_object;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_ref (value->data[0].v_pointer);
#line 1242 "TaskTimer.c"
	} else {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		value->data[0].v_pointer = NULL;
#line 1246 "TaskTimer.c"
	}
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (old) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_unref (old);
#line 1252 "TaskTimer.c"
	}
}


void value_take_task_timer (GValue* value, gpointer v_object) {
	TaskTimer* old;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TASK_TIMER));
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	old = value->data[0].v_pointer;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (v_object) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_TASK_TIMER));
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		value->data[0].v_pointer = v_object;
#line 1271 "TaskTimer.c"
	} else {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		value->data[0].v_pointer = NULL;
#line 1275 "TaskTimer.c"
	}
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (old) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		task_timer_unref (old);
#line 1281 "TaskTimer.c"
	}
}


static void task_timer_class_init (TaskTimerClass * klass) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	task_timer_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	((TaskTimerClass *) klass)->finalize = task_timer_finalize;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_type_class_add_private (klass, sizeof (TaskTimerPrivate));
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_new ("timer_updated", TYPE_TASK_TIMER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOXED, G_TYPE_NONE, 1, G_TYPE_DATE_TIME);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_new ("timer_updated_relative", TYPE_TASK_TIMER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__DOUBLE, G_TYPE_NONE, 1, G_TYPE_DOUBLE);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_new ("timer_running_changed", TYPE_TASK_TIMER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOOLEAN, G_TYPE_NONE, 1, G_TYPE_BOOLEAN);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_new ("timer_almost_over", TYPE_TASK_TIMER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOXED, G_TYPE_NONE, 1, G_TYPE_DATE_TIME);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_new ("timer_finished", TYPE_TASK_TIMER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOOLEAN, G_TYPE_NONE, 1, G_TYPE_BOOLEAN);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_new ("active_task_done", TYPE_TASK_TIMER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, TYPE_TODO_TASK);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_new ("active_task_description_changed", TYPE_TASK_TIMER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, TYPE_TODO_TASK);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_new ("active_task_changed", TYPE_TASK_TIMER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__OBJECT_BOOLEAN, G_TYPE_NONE, 2, TYPE_TODO_TASK, G_TYPE_BOOLEAN);
#line 1309 "TaskTimer.c"
}


static void task_timer_instance_init (TaskTimer * self) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv = TASK_TIMER_GET_PRIVATE (self);
#line 23 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->_running = FALSE;
#line 24 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->_break_active = FALSE;
#line 49 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->_previous_runtime = (gint64) 0;
#line 69 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->priv->_almost_over_sent_already = FALSE;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self->ref_count = 1;
#line 1326 "TaskTimer.c"
}


static void task_timer_finalize (TaskTimer* obj) {
	TaskTimer * self;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TASK_TIMER, TaskTimer);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_signal_handlers_destroy (self);
#line 22 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_settings_manager_unref0 (self->priv->settings);
#line 28 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_date_time_unref0 (self->priv->duration_till_end);
#line 48 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_date_time_unref0 (self->start_time);
#line 50 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	_g_object_unref0 (self->priv->_active_task);
#line 1344 "TaskTimer.c"
}


/**
 * The central class for handling and coordinating timer functionality
 */
GType task_timer_get_type (void) {
	static volatile gsize task_timer_type_id__volatile = 0;
	if (g_once_init_enter (&task_timer_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_task_timer_init, value_task_timer_free_value, value_task_timer_copy_value, value_task_timer_peek_pointer, "p", value_task_timer_collect_value, "p", value_task_timer_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TaskTimerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) task_timer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TaskTimer), 0, (GInstanceInitFunc) task_timer_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType task_timer_type_id;
		task_timer_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TaskTimer", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&task_timer_type_id__volatile, task_timer_type_id);
	}
	return task_timer_type_id__volatile;
}


gpointer task_timer_ref (gpointer instance) {
	TaskTimer* self;
	self = instance;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	g_atomic_int_inc (&self->ref_count);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	return instance;
#line 1372 "TaskTimer.c"
}


void task_timer_unref (gpointer instance) {
	TaskTimer* self;
	self = instance;
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		TASK_TIMER_GET_CLASS (self)->finalize (self);
#line 21 "/home/mark/projects/Go-For-It/src/TaskTimer.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1385 "TaskTimer.c"
	}
}



