/* TxtUtils.c generated by valac 0.34.7, the Vala compiler
 * generated from TxtUtils.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>

#define _g_match_info_unref0(var) ((var == NULL) ? NULL : (var = (g_match_info_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))



gboolean gofi_txt_utils_is_date (const gchar* token);
gboolean gofi_txt_utils_is_priority (const gchar* token);
gboolean gofi_txt_utils_is_project_tag (const gchar* token);
gboolean gofi_txt_utils_is_context_tag (const gchar* token);
gboolean gofi_txt_utils_consume_status (gchar** txt_line);
gchar* gofi_txt_utils_consume_priority (gchar** pseudo_description);
GDateTime* gofi_txt_utils_string_to_date (const gchar* date_txt);
gchar* gofi_txt_utils_date_to_string (GDateTime* date);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

static GRegex* _tmp_regex_0 = NULL;
static GRegex* _tmp_regex_1 = NULL;

/**
     * Checks whether token is a date in the todo.txt format.
     */
static inline GRegex* _thread_safe_regex_init (GRegex** re, const gchar * pattern, GRegexMatchFlags match_options) {
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	if (g_once_init_enter ((volatile gsize*) re)) {
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		GRegex* val = g_regex_new (pattern, match_options, 0, NULL);
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		g_once_init_leave ((volatile gsize*) re, (gsize) val);
#line 43 "TxtUtils.c"
	}
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	return *re;
#line 47 "TxtUtils.c"
}


gboolean gofi_txt_utils_is_date (const gchar* token) {
	gboolean result = FALSE;
	GMatchInfo* info = NULL;
	const gchar* _tmp0_ = NULL;
	GMatchInfo* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
#line 5 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	g_return_val_if_fail (token != NULL, FALSE);
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp0_ = token;
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp2_ = g_regex_match (_thread_safe_regex_init (&_tmp_regex_0, "\\d\\d\\d\\d-\\d\\d-\\d\\d", 0), _tmp0_, 0, &_tmp1_);
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_g_match_info_unref0 (info);
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	info = _tmp1_;
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	result = _tmp2_;
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_g_match_info_unref0 (info);
#line 7 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	return result;
#line 73 "TxtUtils.c"
}


/**
     * Checks whether token is a priority in the todo.txt format.
     */
gboolean gofi_txt_utils_is_priority (const gchar* token) {
	gboolean result = FALSE;
	GMatchInfo* info = NULL;
	const gchar* _tmp0_ = NULL;
	GMatchInfo* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
#line 13 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	g_return_val_if_fail (token != NULL, FALSE);
#line 15 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp0_ = token;
#line 15 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp2_ = g_regex_match (_thread_safe_regex_init (&_tmp_regex_1, "\\([A-Z]\\)", 0), _tmp0_, 0, &_tmp1_);
#line 15 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_g_match_info_unref0 (info);
#line 15 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	info = _tmp1_;
#line 15 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	result = _tmp2_;
#line 15 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_g_match_info_unref0 (info);
#line 15 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	return result;
#line 102 "TxtUtils.c"
}


/**
     * Checks whether token is a project tag in the todo.txt format.
     */
static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
#line 1086 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, '\0');
#line 1087 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp0_ = index;
#line 1087 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp1_ = ((gchar*) self)[_tmp0_];
#line 1087 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	result = _tmp1_;
#line 1087 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	return result;
#line 123 "TxtUtils.c"
}


gboolean gofi_txt_utils_is_project_tag (const gchar* token) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	gchar _tmp2_ = '\0';
#line 21 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	g_return_val_if_fail (token != NULL, FALSE);
#line 22 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp1_ = token;
#line 22 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp2_ = string_get (_tmp1_, (glong) 0);
#line 22 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	if (_tmp2_ == '+') {
#line 140 "TxtUtils.c"
		const gchar* _tmp3_ = NULL;
		gchar _tmp4_ = '\0';
#line 22 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp3_ = token;
#line 22 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp4_ = string_get (_tmp3_, (glong) 1);
#line 22 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp0_ = ((gint) _tmp4_) > 33;
#line 149 "TxtUtils.c"
	} else {
#line 22 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp0_ = FALSE;
#line 153 "TxtUtils.c"
	}
#line 22 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	result = _tmp0_;
#line 22 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	return result;
#line 159 "TxtUtils.c"
}


/**
     * Checks whether token is a context tag in the todo.txt format.
     */
gboolean gofi_txt_utils_is_context_tag (const gchar* token) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	gchar _tmp2_ = '\0';
#line 28 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	g_return_val_if_fail (token != NULL, FALSE);
#line 29 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp1_ = token;
#line 29 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp2_ = string_get (_tmp1_, (glong) 0);
#line 29 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	if (_tmp2_ == '@') {
#line 179 "TxtUtils.c"
		const gchar* _tmp3_ = NULL;
		gchar _tmp4_ = '\0';
#line 29 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp3_ = token;
#line 29 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp4_ = string_get (_tmp3_, (glong) 1);
#line 29 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp0_ = ((gint) _tmp4_) > 33;
#line 188 "TxtUtils.c"
	} else {
#line 29 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp0_ = FALSE;
#line 192 "TxtUtils.c"
	}
#line 29 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	result = _tmp0_;
#line 29 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	return result;
#line 198 "TxtUtils.c"
}


/**
     * Removes x from the start of finished tasks
     */
gboolean gofi_txt_utils_consume_status (gchar** txt_line) {
	gboolean result = FALSE;
	gboolean done = FALSE;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
#line 35 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	g_return_val_if_fail (*txt_line != NULL, FALSE);
#line 36 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp0_ = *txt_line;
#line 36 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp1_ = g_str_has_prefix (_tmp0_, "x ");
#line 36 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	done = _tmp1_;
#line 38 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp2_ = done;
#line 38 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	if (_tmp2_) {
#line 223 "TxtUtils.c"
		const gchar* _tmp3_ = NULL;
		gchar** _tmp4_ = NULL;
		gchar** _tmp5_ = NULL;
		gchar** _tmp6_ = NULL;
		gint _tmp6__length1 = 0;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
#line 40 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp3_ = *txt_line;
#line 40 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp5_ = _tmp4_ = g_strsplit (_tmp3_, "x ", 2);
#line 40 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp6_ = _tmp5_;
#line 40 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp6__length1 = _vala_array_length (_tmp4_);
#line 40 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp7_ = _tmp6_[1];
#line 40 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp8_ = g_strdup (_tmp7_);
#line 40 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_g_free0 (*txt_line);
#line 40 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		*txt_line = _tmp8_;
#line 40 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp6_ = (_vala_array_free (_tmp6_, _tmp6__length1, (GDestroyNotify) g_free), NULL);
#line 249 "TxtUtils.c"
	}
#line 43 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	result = done;
#line 43 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	return result;
#line 255 "TxtUtils.c"
}


/**
     * Removes and returns the priority from pseudo descriptions (task lines 
     * consisting of at most a priority and a description)
     */
gchar* gofi_txt_utils_consume_priority (gchar** pseudo_description) {
	gchar* result = NULL;
	gchar** parts = NULL;
	const gchar* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint parts_length1 = 0;
	gint _parts_size_ = 0;
	gboolean _tmp3_ = FALSE;
	gchar** _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	const gchar* _tmp5_ = NULL;
#line 50 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	g_return_val_if_fail (*pseudo_description != NULL, NULL);
#line 51 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp0_ = *pseudo_description;
#line 51 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp2_ = _tmp1_ = g_strsplit (_tmp0_, " ", 2);
#line 51 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	parts = _tmp2_;
#line 51 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	parts_length1 = _vala_array_length (_tmp1_);
#line 51 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_parts_size_ = parts_length1;
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp4_ = parts;
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp4__length1 = parts_length1;
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp5_ = _tmp4_[1];
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	if (_tmp5_ != NULL) {
#line 295 "TxtUtils.c"
		gchar** _tmp6_ = NULL;
		gint _tmp6__length1 = 0;
		const gchar* _tmp7_ = NULL;
		gboolean _tmp8_ = FALSE;
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp6_ = parts;
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp6__length1 = parts_length1;
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp7_ = _tmp6_[0];
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp8_ = gofi_txt_utils_is_priority (_tmp7_);
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp3_ = _tmp8_;
#line 310 "TxtUtils.c"
	} else {
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp3_ = FALSE;
#line 314 "TxtUtils.c"
	}
#line 52 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	if (_tmp3_) {
#line 318 "TxtUtils.c"
		gchar** _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		const gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		gchar** _tmp12_ = NULL;
		gint _tmp12__length1 = 0;
		const gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
#line 53 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp9_ = parts;
#line 53 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp9__length1 = parts_length1;
#line 53 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp10_ = _tmp9_[1];
#line 53 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp11_ = g_strdup (_tmp10_);
#line 53 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_g_free0 (*pseudo_description);
#line 53 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		*pseudo_description = _tmp11_;
#line 54 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp12_ = parts;
#line 54 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp12__length1 = parts_length1;
#line 54 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp13_ = _tmp12_[0];
#line 54 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		_tmp14_ = g_strdup (_tmp13_);
#line 54 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		result = _tmp14_;
#line 54 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
#line 54 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		return result;
#line 353 "TxtUtils.c"
	} else {
#line 56 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		result = NULL;
#line 56 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
#line 56 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
		return result;
#line 361 "TxtUtils.c"
	}
#line 50 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
#line 365 "TxtUtils.c"
}


GDateTime* gofi_txt_utils_string_to_date (const gchar* date_txt) {
	GDateTime* result = NULL;
	gchar** date_parts = NULL;
	const gchar* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint date_parts_length1 = 0;
	gint _date_parts_size_ = 0;
	const gchar* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	const gchar* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	const gchar* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	GDateTime* _tmp9_ = NULL;
#line 60 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	g_return_val_if_fail (date_txt != NULL, NULL);
#line 61 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp0_ = date_txt;
#line 61 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp2_ = _tmp1_ = g_strsplit (_tmp0_, "-", 3);
#line 61 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	date_parts = _tmp2_;
#line 61 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	date_parts_length1 = _vala_array_length (_tmp1_);
#line 61 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_date_parts_size_ = date_parts_length1;
#line 62 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp3_ = date_parts[0];
#line 62 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp4_ = atoi (_tmp3_);
#line 62 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp5_ = date_parts[1];
#line 62 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp6_ = atoi (_tmp5_);
#line 62 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp7_ = date_parts[2];
#line 62 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp8_ = atoi (_tmp7_);
#line 62 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp9_ = g_date_time_new_local (_tmp4_, _tmp6_, _tmp8_, 0, 0, (gdouble) 0);
#line 62 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	result = _tmp9_;
#line 62 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	date_parts = (_vala_array_free (date_parts, date_parts_length1, (GDestroyNotify) g_free), NULL);
#line 62 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	return result;
#line 416 "TxtUtils.c"
}


gchar* gofi_txt_utils_date_to_string (GDateTime* date) {
	gchar* result = NULL;
	GDateTime* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 70 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	g_return_val_if_fail (date != NULL, NULL);
#line 71 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp0_ = date;
#line 71 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	_tmp1_ = g_date_time_format (_tmp0_, "%Y-%m-%d");
#line 71 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	result = _tmp1_;
#line 71 "/home/mark/projects/Go-For-It/src/TxtUtils.vala"
	return result;
#line 434 "TxtUtils.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



